# Generated by Django 4.2.26 on 2025-12-02 14:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("normal", "通常出勤"),
                            ("paid_leave", "有給休暇"),
                            ("sick_leave", "病欠"),
                            ("absent", "欠勤"),
                            ("late", "遅刻"),
                            ("early_leave", "早退"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="勤怠種別",
                    ),
                ),
                (
                    "clock_in",
                    models.TimeField(blank=True, null=True, verbose_name="出勤時刻"),
                ),
                (
                    "clock_out",
                    models.TimeField(blank=True, null=True, verbose_name="退勤時刻"),
                ),
                (
                    "break_minutes",
                    models.IntegerField(default=0, verbose_name="休憩時間（分）"),
                ),
                (
                    "work_minutes",
                    models.IntegerField(default=0, verbose_name="勤務時間（分）"),
                ),
                (
                    "overtime_minutes",
                    models.IntegerField(default=0, verbose_name="残業時間（分）"),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="遅刻時間（分）"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="早退時間（分）"),
                ),
                (
                    "lesson_count",
                    models.IntegerField(default=0, verbose_name="授業コマ数"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="承認済み"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "勤怠記録",
                "verbose_name_plural": "勤怠記録",
                "db_table": "t40_attendances",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(verbose_name="月")),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="支払日"),
                ),
                ("work_days", models.IntegerField(default=0, verbose_name="出勤日数")),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="勤務時間",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="残業時間",
                    ),
                ),
                (
                    "lesson_count",
                    models.IntegerField(default=0, verbose_name="授業コマ数"),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="総支給額",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="控除合計",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="手取額",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("calculated", "計算済み"),
                            ("approved", "承認済み"),
                            ("paid", "支払済み"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="計算日時"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支払日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "給与明細",
                "verbose_name_plural": "給与明細",
                "db_table": "t47_payrolls",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="PayrollDetail",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="金額"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "給与明細項目",
                "verbose_name_plural": "給与明細項目",
                "db_table": "t47_payroll_details",
            },
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(max_length=20, verbose_name="項目コード"),
                ),
                ("item_name", models.CharField(max_length=100, verbose_name="項目名")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("earning", "支給"), ("deduction", "控除")],
                        max_length=20,
                        verbose_name="項目種別",
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "固定"),
                            ("percentage", "割合"),
                            ("formula", "計算式"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="計算種別",
                    ),
                ),
                (
                    "default_value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="デフォルト値",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="課税対象"),
                ),
                (
                    "is_social_insurance_target",
                    models.BooleanField(default=True, verbose_name="社会保険対象"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "給与項目",
                "verbose_name_plural": "給与項目",
                "db_table": "t48_payroll_items",
                "ordering": ["item_type", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SalaryMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("hourly", "時給"),
                            ("per_lesson", "コマ給"),
                            ("monthly", "月給"),
                        ],
                        default="hourly",
                        max_length=20,
                        verbose_name="給与種別",
                    ),
                ),
                (
                    "base_hourly_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="基本時給",
                    ),
                ),
                (
                    "base_lesson_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="基本コマ給",
                    ),
                ),
                (
                    "base_monthly_salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="基本月給",
                    ),
                ),
                (
                    "transportation_allowance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="交通費",
                    ),
                ),
                (
                    "overtime_rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.25"),
                        max_digits=4,
                        verbose_name="残業割増率",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="適用開始日")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="適用終了日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "給与マスタ",
                "verbose_name_plural": "給与マスタ",
                "db_table": "t46_salary_masters",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "break_minutes",
                    models.IntegerField(default=0, verbose_name="休憩時間（分）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("requested", "申請中"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "シフト",
                "verbose_name_plural": "シフト",
                "db_table": "t41_shifts",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "staff_no",
                    models.CharField(max_length=20, verbose_name="スタッフ番号"),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="姓")),
                ("first_name", models.CharField(max_length=50, verbose_name="名")),
                (
                    "last_name_kana",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="姓（カナ）"
                    ),
                ),
                (
                    "first_name_kana",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="名（カナ）"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, verbose_name="表示名"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "phone_mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="携帯電話"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
                ),
                (
                    "prefecture",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="都道府県"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="市区町村"
                    ),
                ),
                (
                    "address1",
                    models.CharField(blank=True, max_length=100, verbose_name="住所1"),
                ),
                (
                    "address2",
                    models.CharField(blank=True, max_length=100, verbose_name="住所2"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生年月日"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=10, verbose_name="性別"),
                ),
                (
                    "profile_image_url",
                    models.URLField(blank=True, verbose_name="プロフィール画像URL"),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("full_time", "正社員"),
                            ("part_time", "アルバイト"),
                            ("contract", "契約社員"),
                            ("temp", "派遣社員"),
                        ],
                        default="part_time",
                        max_length=20,
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("teacher", "講師"),
                            ("senior_teacher", "主任講師"),
                            ("manager", "教室長"),
                            ("area_manager", "エリアマネージャー"),
                            ("admin", "事務"),
                            ("executive", "役員"),
                        ],
                        default="teacher",
                        max_length=20,
                        verbose_name="役職",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入社日"),
                ),
                (
                    "retirement_date",
                    models.DateField(blank=True, null=True, verbose_name="退職日"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在籍中"),
                            ("on_leave", "休職中"),
                            ("retired", "退職"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=50, verbose_name="銀行名"),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=50, verbose_name="支店名"),
                ),
                (
                    "bank_account_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="口座種別"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="口座番号"
                    ),
                ),
                (
                    "bank_account_holder",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="口座名義"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="カスタムフィールド"
                    ),
                ),
                (
                    "primary_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_staff",
                        to="schools.school",
                        verbose_name="主所属校舎",
                    ),
                ),
                (
                    "teachable_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachable_staff",
                        to="schools.subject",
                        verbose_name="指導可能教科",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ",
                "verbose_name_plural": "スタッフ",
                "db_table": "t28_staff",
                "ordering": ["-hire_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffSchool",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主所属"),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_assignments",
                        to="hr.staff",
                        verbose_name="スタッフ",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ所属校舎",
                "verbose_name_plural": "スタッフ所属校舎",
                "db_table": "t28_staff_schools",
            },
        ),
    ]
