# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザーアカウント",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="hr.staff",
                verbose_name="スタッフ",
            ),
        ),
        migrations.AddField(
            model_name="salarymaster",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_masters",
                to="hr.staff",
                verbose_name="スタッフ",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollitem",
            unique_together={("tenant_id", "item_code")},
        ),
        migrations.AddField(
            model_name="payrolldetail",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_details",
                to="hr.payrollitem",
                verbose_name="給与項目",
            ),
        ),
        migrations.AddField(
            model_name="payrolldetail",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="hr.payroll",
                verbose_name="給与明細",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="承認者",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payrolls",
                to="hr.staff",
                verbose_name="スタッフ",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="承認者",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_attendances",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="hr.shift",
                verbose_name="シフト",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.staff",
                verbose_name="スタッフ",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffschool",
            unique_together={("staff", "school")},
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together={("tenant_id", "staff_no")},
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["staff", "date"], name="t41_shifts_staff_i_4db21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["school", "date"], name="t41_shifts_school__47dfea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("tenant_id", "staff", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["staff", "date"], name="t40_attenda_staff_i_3e149b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("staff", "date", "school")},
        ),
    ]
