# Generated by Django 4.2.27 on 2025-12-07
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        # T12: ブランドマスタ
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand_code",
                    models.CharField(max_length=20, verbose_name="ブランドコード"),
                ),
                (
                    "brand_name",
                    models.CharField(max_length=100, verbose_name="ブランド名"),
                ),
                (
                    "brand_name_short",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ブランド名略称"
                    ),
                ),
                (
                    "brand_type",
                    models.CharField(blank=True, max_length=20, verbose_name="ブランド種別"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("logo_url", models.URLField(blank=True, verbose_name="ロゴURL")),
                (
                    "color_primary",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="プライマリカラー"
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="セカンダリカラー"
                    ),
                ),
                (
                    "grade_update_month",
                    models.IntegerField(
                        default=4,
                        help_text="学年が上がる月（1-12）。例：4月なら4",
                        verbose_name="学年更新月",
                    ),
                ),
                (
                    "grade_update_day",
                    models.IntegerField(
                        default=1,
                        help_text="学年が上がる日（1-31）。例：1日なら1",
                        verbose_name="学年更新日",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T12_ブランド",
                "verbose_name_plural": "T12_ブランド",
                "db_table": "t12_brands",
                "ordering": ["sort_order", "brand_code"],
                "unique_together": {("tenant_id", "brand_code")},
            },
        ),
        # T10: 校舎マスタ
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "school_code",
                    models.CharField(max_length=20, verbose_name="校舎コード"),
                ),
                (
                    "school_name",
                    models.CharField(max_length=100, verbose_name="校舎名"),
                ),
                (
                    "school_name_short",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="校舎名略称"
                    ),
                ),
                (
                    "school_type",
                    models.CharField(blank=True, max_length=20, verbose_name="校舎種別"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
                ),
                (
                    "prefecture",
                    models.CharField(blank=True, max_length=10, verbose_name="都道府県"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="市区町村"),
                ),
                (
                    "address1",
                    models.CharField(blank=True, max_length=100, verbose_name="住所1"),
                ),
                (
                    "address2",
                    models.CharField(blank=True, max_length=100, verbose_name="住所2"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="FAX番号"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="メールアドレス"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="緯度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="経度",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="定員"),
                ),
                (
                    "opening_date",
                    models.DateField(blank=True, null=True, verbose_name="開校日"),
                ),
                (
                    "closing_date",
                    models.DateField(blank=True, null=True, verbose_name="閉校日"),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="校舎設定"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T10_校舎",
                "verbose_name_plural": "T10_校舎",
                "db_table": "t10_schools",
                "ordering": ["sort_order", "school_code"],
                "unique_together": {("tenant_id", "school_code")},
            },
        ),
        # T11: 教室マスタ
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "classroom_code",
                    models.CharField(max_length=20, verbose_name="教室コード"),
                ),
                (
                    "classroom_name",
                    models.CharField(max_length=50, verbose_name="教室名"),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="定員"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="階"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T11_教室",
                "verbose_name_plural": "T11_教室",
                "db_table": "t11_classrooms",
                "ordering": ["school", "sort_order", "classroom_code"],
                "unique_together": {("school", "classroom_code")},
            },
        ),
        # T18: 教科マスタ
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(max_length=20, verbose_name="教科コード"),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=50, verbose_name="教科名"),
                ),
                (
                    "subject_name_short",
                    models.CharField(blank=True, max_length=10, verbose_name="教科名略称"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="カラーコード"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T18_教科",
                "verbose_name_plural": "T18_教科",
                "db_table": "t18_subjects",
                "ordering": ["sort_order", "subject_code"],
                "unique_together": {("tenant_id", "subject_code")},
            },
        ),
        # T17: 学年マスタ
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade_code",
                    models.CharField(max_length=10, verbose_name="学年コード"),
                ),
                (
                    "grade_name",
                    models.CharField(max_length=50, verbose_name="対象学年名"),
                ),
                (
                    "grade_name_short",
                    models.CharField(blank=True, max_length=20, verbose_name="略称"),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=20, verbose_name="カテゴリ"),
                ),
                (
                    "school_year",
                    models.IntegerField(blank=True, null=True, verbose_name="学校学年"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T17_対象学年定義",
                "verbose_name_plural": "T17_対象学年定義",
                "db_table": "t17_grades",
                "ordering": ["sort_order", "grade_code"],
                "unique_together": {("tenant_id", "grade_code")},
            },
        ),
    ]
