# Generated by Django 4.2.26 on 2025-12-03 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_packitem"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_code",
                    models.CharField(max_length=20, verbose_name="時間帯コード"),
                ),
                ("slot_name", models.CharField(max_length=50, verbose_name="時間帯名")),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "duration_minutes",
                    models.IntegerField(default=50, verbose_name="時間（分）"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T13_時間帯",
                "verbose_name_plural": "T13_時間帯",
                "db_table": "t13_time_slots",
                "ordering": ["sort_order", "start_time"],
                "unique_together": {("tenant_id", "slot_code")},
            },
        ),
        migrations.CreateModel(
            name="SchoolSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "月曜日"),
                            (2, "火曜日"),
                            (3, "水曜日"),
                            (4, "木曜日"),
                            (5, "金曜日"),
                            (6, "土曜日"),
                            (7, "日曜日"),
                        ],
                        verbose_name="曜日",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(default=10, verbose_name="定員（席数）"),
                ),
                (
                    "reserved_seats",
                    models.IntegerField(default=0, verbose_name="予約済み席数"),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="有効開始日"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="有効終了日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="schools.timeslot",
                        verbose_name="時間帯",
                    ),
                ),
            ],
            options={
                "verbose_name": "T14_校舎開講スケジュール",
                "verbose_name_plural": "T14_校舎開講スケジュール",
                "db_table": "t14_school_schedules",
                "ordering": ["school", "day_of_week", "time_slot__start_time"],
                "unique_together": {("brand", "school", "day_of_week", "time_slot")},
            },
        ),
        migrations.CreateModel(
            name="SchoolCourse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capacity_override",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="席数上書き"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="開講開始日"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="開講終了日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_courses",
                        to="contracts.course",
                        verbose_name="コース",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="schools.schoolschedule",
                        verbose_name="開講スケジュール",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_courses",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
            ],
            options={
                "verbose_name": "T15_校舎別コース",
                "verbose_name_plural": "T15_校舎別コース",
                "db_table": "t15_school_courses",
                "ordering": ["school", "course"],
                "unique_together": {("school", "course", "schedule")},
            },
        ),
    ]
