# Generated by Django 4.2.26 on 2025-12-03 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_timeslot_schoolschedule_schoolcourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClosure",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("closure_date", models.DateField(verbose_name="休講日")),
                (
                    "closure_type",
                    models.CharField(
                        choices=[
                            ("school_closed", "校舎休校"),
                            ("brand_closed", "ブランド休講"),
                            ("schedule_closed", "時間帯休講"),
                            ("holiday", "祝日休講"),
                            ("maintenance", "メンテナンス"),
                            ("weather", "天候不良"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="休講種別",
                    ),
                ),
                (
                    "has_makeup",
                    models.BooleanField(default=False, verbose_name="振替あり"),
                ),
                (
                    "makeup_date",
                    models.DateField(blank=True, null=True, verbose_name="振替日"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="休講理由"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="通知日時"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="指定しない場合は全ブランド",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "makeup_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_closures",
                        to="schools.schoolschedule",
                        verbose_name="振替スケジュール",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="特定の曜日・時間帯のみ休講の場合",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="schools.schoolschedule",
                        verbose_name="スケジュール",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="指定しない場合は全校舎",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
            ],
            options={
                "verbose_name": "T16_休講",
                "verbose_name_plural": "T16_休講",
                "db_table": "t16_school_closures",
                "ordering": ["-closure_date"],
            },
        ),
    ]
