# Generated by Django 4.2.26 on 2025-12-03 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_schoolclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year_code",
                    models.CharField(max_length=10, verbose_name="学年コード"),
                ),
                ("year_name", models.CharField(max_length=20, verbose_name="学年名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("infant", "乳幼児"),
                            ("preschool", "未就学児"),
                            ("elementary", "小学生"),
                            ("junior_high", "中学生"),
                            ("high_school", "高校生"),
                            ("university", "大学生"),
                            ("adult", "社会人"),
                        ],
                        default="elementary",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T17a_単一学年",
                "verbose_name_plural": "T17a_単一学年",
                "db_table": "t17a_school_years",
                "ordering": ["sort_order"],
                "unique_together": {("tenant_id", "year_code")},
            },
        ),
        migrations.CreateModel(
            name="GradeSchoolYear",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_school_years",
                        to="schools.grade",
                        verbose_name="対象学年",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_school_years",
                        to="schools.schoolyear",
                        verbose_name="単一学年",
                    ),
                ),
            ],
            options={
                "verbose_name": "T17b_対象学年_単一学年",
                "verbose_name_plural": "T17b_対象学年_単一学年",
                "db_table": "t17b_grade_school_years",
                "unique_together": {("tenant_id", "grade", "school_year")},
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="school_years",
            field=models.ManyToManyField(
                related_name="grades",
                through="schools.GradeSchoolYear",
                to="schools.schoolyear",
                verbose_name="対象学年",
            ),
        ),
    ]
