# Generated by Django 4.2.26 on 2025-12-03 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_brand_to_school_brand(apps, schema_editor):
    """既存のSchool.brandをSchoolBrandに移行"""
    School = apps.get_model('schools', 'School')
    SchoolBrand = apps.get_model('schools', 'SchoolBrand')

    for school in School.objects.all():
        if hasattr(school, 'brand_id') and school.brand_id:
            SchoolBrand.objects.create(
                id=uuid.uuid4(),
                school=school,
                brand_id=school.brand_id,
                tenant_id=school.tenant_id,
                is_primary=True,
                sort_order=0,
            )


def reverse_migrate(apps, schema_editor):
    """逆移行（SchoolBrandからSchool.brandへ）"""
    pass  # データは失われるので空実装


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_add_school_year_models"),
    ]

    operations = [
        # 1. まずSchoolBrandテーブルを作成
        migrations.CreateModel(
            name="SchoolBrand",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="この校舎の代表ブランド",
                        verbose_name="主ブランド",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_brands",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_brands",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
            ],
            options={
                "verbose_name": "T10b_校舎ブランド",
                "verbose_name_plural": "T10b_校舎ブランド",
                "db_table": "t10b_school_brands",
                "ordering": ["sort_order"],
                "unique_together": {("school", "brand")},
            },
        ),
        # 2. 既存データを移行
        migrations.RunPython(migrate_brand_to_school_brand, reverse_migrate),
        # 3. 古いbrandフィールドは既に0001_initialで削除済み
        # 4. ManyToManyフィールドを追加
        migrations.AddField(
            model_name="school",
            name="brands",
            field=models.ManyToManyField(
                related_name="schools",
                through="schools.SchoolBrand",
                to="schools.brand",
                verbose_name="所属ブランド",
            ),
        ),
    ]
