# Generated by Django 4.2.26 on 2025-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_school_multiple_brands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="capacity",
            field=models.IntegerField(default=1, verbose_name="Room定員"),
        ),
    ]
