# Generated by Django 4.2.26 on 2025-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_classroom_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="grade_update_day",
            field=models.IntegerField(
                default=1,
                help_text="学年が上がる日（1-31）。例：1日なら1",
                verbose_name="学年更新日",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="grade_update_month",
            field=models.IntegerField(
                default=4,
                help_text="学年が上がる月（1-12）。例：4月なら4",
                verbose_name="学年更新月",
            ),
        ),
    ]
