# Generated by Django 4.2.27 on 2025-12-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_add_tenant_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="brands",
        ),
        migrations.DeleteModel(
            name="SchoolBrand",
        ),
    ]
