# Generated by Django 4.2.27 on 2025-12-08 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("schools", "0008_add_brand_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": ["sort_order", "classroom_code"],
                "verbose_name": "T11_教室",
                "verbose_name_plural": "T11_教室",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["sort_order", "subject_code"],
                "verbose_name": "教科",
                "verbose_name_plural": "教科",
            },
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="notes",
        ),
        migrations.AddField(
            model_name="classroom",
            name="equipment",
            field=models.JSONField(blank=True, default=list, verbose_name="設備"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="room_type",
            field=models.CharField(blank=True, max_length=20, verbose_name="教室種別"),
        ),
        migrations.AddField(
            model_name="schoolschedule",
            name="calendar_pattern",
            field=models.CharField(
                blank=True,
                help_text="例: 1001_AEC_A, 1002_AEC_B, 1003_AEC_P",
                max_length=50,
                verbose_name="カレンダーパターン",
            ),
        ),
        migrations.AddField(
            model_name="schoolschedule",
            name="pause_seat_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="休会時座席料金",
            ),
        ),
        migrations.AddField(
            model_name="schoolschedule",
            name="trial_capacity",
            field=models.IntegerField(default=2, verbose_name="体験受入可能数"),
        ),
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.CharField(
                choices=[
                    ("main", "主要教科"),
                    ("sub", "副教科"),
                    ("special", "特別講座"),
                    ("other", "その他"),
                ],
                default="main",
                max_length=20,
                verbose_name="教科カテゴリ",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="icon",
            field=models.CharField(blank=True, max_length=50, verbose_name="アイコン"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="floor",
            field=models.CharField(blank=True, max_length=10, verbose_name="階数"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="color",
            field=models.CharField(blank=True, max_length=7, verbose_name="表示色"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name_short",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="教科名略称"
            ),
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.CreateModel(
            name="BrandCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_code",
                    models.CharField(max_length=20, verbose_name="カテゴリコード"),
                ),
                (
                    "category_name",
                    models.CharField(max_length=100, verbose_name="カテゴリ名"),
                ),
                (
                    "category_name_short",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="カテゴリ名略称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("logo_url", models.URLField(blank=True, verbose_name="ロゴURL")),
                (
                    "color_primary",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="プライマリカラー"
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="セカンダリカラー"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T12c_ブランドカテゴリ",
                "verbose_name_plural": "T12c_ブランドカテゴリ",
                "db_table": "t12c_brand_categories",
                "ordering": ["sort_order", "category_code"],
                "unique_together": {("tenant_id", "category_code")},
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="schools.brandcategory",
                verbose_name="ブランドカテゴリ",
            ),
        ),
        migrations.CreateModel(
            name="LessonCalendar",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calendar_code",
                    models.CharField(max_length=50, verbose_name="カレンダーコード"),
                ),
                ("lesson_date", models.DateField(verbose_name="授業日")),
                ("day_of_week", models.CharField(max_length=10, verbose_name="曜日")),
                ("is_open", models.BooleanField(default=False, verbose_name="開講日")),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("A", "Aパターン（外国人講師あり）"),
                            ("B", "Bパターン（日本人講師のみ）"),
                            ("closed", "休講"),
                        ],
                        default="closed",
                        max_length=10,
                        verbose_name="授業タイプ",
                    ),
                ),
                (
                    "display_label",
                    models.CharField(
                        blank=True,
                        help_text="例: 水A1, 木B2など",
                        max_length=20,
                        verbose_name="保護者カレンダー表示",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True,
                        help_text="A, Bなど",
                        max_length=10,
                        verbose_name="チケット券種",
                    ),
                ),
                (
                    "ticket_sequence",
                    models.IntegerField(
                        blank=True,
                        help_text="月内の何回目か",
                        null=True,
                        verbose_name="チケット番号",
                    ),
                ),
                (
                    "is_makeup_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="振替拒否の場合はFalse",
                        verbose_name="振替許可",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="振替拒否理由"
                    ),
                ),
                (
                    "ticket_issue_count",
                    models.IntegerField(
                        blank=True,
                        help_text="発行するチケット数",
                        null=True,
                        verbose_name="権利発券数",
                    ),
                ),
                (
                    "valid_days",
                    models.IntegerField(default=90, verbose_name="有効日数"),
                ),
                (
                    "notice_message",
                    models.TextField(blank=True, verbose_name="お知らせ"),
                ),
                (
                    "auto_send_notice",
                    models.BooleanField(default=False, verbose_name="自動お知らせ送信"),
                ),
                (
                    "holiday_name",
                    models.CharField(blank=True, max_length=50, verbose_name="祝日名"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_calendars",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_calendars",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T13_開講カレンダー",
                "verbose_name_plural": "T13_開講カレンダー",
                "db_table": "t13_lesson_calendars",
                "ordering": ["lesson_date", "brand", "school"],
                "unique_together": {("tenant_id", "brand", "school", "lesson_date")},
            },
        ),
    ]
