# Generated by Django 4.2.27 on 2025-12-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_remove_school_brands"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="schools.brand",
                verbose_name="ブランド",
            ),
        ),
    ]
