# Generated by Django 4.2.27 on 2025-12-06 02:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("schools", "0010_add_brand_to_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandSchool",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="このブランドのメイン校舎かどうか",
                        verbose_name="メイン校舎",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_schools",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_schools",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T12a_ブランド開講校舎",
                "verbose_name_plural": "T12a_ブランド開講校舎",
                "db_table": "t12a_brand_schools",
                "ordering": ["brand", "sort_order", "school__school_name"],
                "unique_together": {("tenant_id", "brand", "school")},
            },
        ),
    ]
