# Generated by Django 4.2.26 on 2025-12-10 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("schools", "0011_alter_lessoncalendar_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classschedule",
            name="unique_class_schedule_code",
        ),
        migrations.AddField(
            model_name="gradeschoolyear",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="address3",
            field=models.CharField(blank=True, max_length=100, verbose_name="住所3"),
        ),
        migrations.AddField(
            model_name="school",
            name="address_en1",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="住所英語1"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="address_en2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="住所英語2"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="building_owner_info",
            field=models.TextField(blank=True, verbose_name="建物オーナー情報"),
        ),
        migrations.AddField(
            model_name="school",
            name="building_ownership",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="建物所有権"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="customer_parking",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="顧客用駐車場"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="district_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="地区名"),
        ),
        migrations.AddField(
            model_name="school",
            name="district_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="地区No"),
        ),
        migrations.AddField(
            model_name="school",
            name="email_password",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="メールパスワード"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="geofence_range",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ジオフェンス範囲(km)",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="internet_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="インターネットID"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="internet_password",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="インターネットパスワード"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="key_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="キー番号"),
        ),
        migrations.AddField(
            model_name="school",
            name="management_company",
            field=models.TextField(blank=True, verbose_name="管理会社"),
        ),
        migrations.AddField(
            model_name="school",
            name="map_link",
            field=models.URLField(blank=True, verbose_name="Map Link"),
        ),
        migrations.AddField(
            model_name="school",
            name="map_pin",
            field=models.URLField(blank=True, verbose_name="MAP Pin"),
        ),
        migrations.AddField(
            model_name="school",
            name="notes",
            field=models.TextField(blank=True, verbose_name="メモ"),
        ),
        migrations.AddField(
            model_name="school",
            name="padlock",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="パドロック"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="pc_account",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="PCアカウント"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="pc_password",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="PCパスワード"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="room_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="部屋数"),
        ),
        migrations.AddField(
            model_name="school",
            name="school_name_romaji",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="校舎ローマ字名"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="teacher_parking",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="教師用駐車場"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="transfer_date1",
            field=models.DateField(blank=True, null=True, verbose_name="校舎移転日1"),
        ),
        migrations.AddField(
            model_name="school",
            name="transfer_date2",
            field=models.DateField(blank=True, null=True, verbose_name="校舎移転日2"),
        ),
        migrations.AddField(
            model_name="school",
            name="transfer_date3",
            field=models.DateField(blank=True, null=True, verbose_name="校舎移転日3"),
        ),
        migrations.AddField(
            model_name="school",
            name="website",
            field=models.URLField(blank=True, verbose_name="ウェブサイト"),
        ),
        migrations.AddField(
            model_name="schoolclosure",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="schoolcourse",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="schoolschedule",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="schoolyear",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="郵便番号"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="schools.brand",
                verbose_name="ブランド",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classschedule",
            unique_together={("tenant_id", "schedule_code")},
        ),
    ]
