# Generated by Django 5.1 manual migration
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_add_grade_to_class_schedule'),
        ('schools', '0008_add_tenant_ref'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankType',
            fields=[
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=10, verbose_name='種別コード')),
                ('type_name', models.CharField(max_length=50, verbose_name='種別名')),
                ('type_label', models.CharField(max_length=20, verbose_name='表示名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '金融機関種別',
                'verbose_name_plural': '金融機関種別',
                'db_table': 'bank_types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(db_index=True, max_length=10, verbose_name='金融機関コード')),
                ('bank_name', models.CharField(max_length=100, verbose_name='金融機関名')),
                ('bank_name_kana', models.CharField(blank=True, max_length=100, verbose_name='金融機関名カナ')),
                ('bank_name_half_kana', models.CharField(blank=True, max_length=100, verbose_name='金融機関名半角カナ')),
                ('bank_name_hiragana', models.CharField(blank=True, max_length=100, verbose_name='金融機関名ひらがな')),
                ('aiueo_row', models.CharField(blank=True, choices=[('あ', 'あ行'), ('か', 'か行'), ('さ', 'さ行'), ('た', 'た行'), ('な', 'な行'), ('は', 'は行'), ('ま', 'ま行'), ('や', 'や行'), ('ら', 'ら行'), ('わ', 'わ行')], db_index=True, help_text='頭文字の行（あ行、か行...）', max_length=2, verbose_name='あいうえお行')),
                ('bank_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='schools.banktype', verbose_name='金融機関種別')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '金融機関',
                'verbose_name_plural': '金融機関',
                'db_table': 'banks',
                'ordering': ['sort_order', 'bank_name_hiragana'],
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.bank', verbose_name='金融機関')),
                ('branch_code', models.CharField(db_index=True, max_length=10, verbose_name='支店コード')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('branch_name_kana', models.CharField(blank=True, max_length=100, verbose_name='支店名カナ')),
                ('branch_name_half_kana', models.CharField(blank=True, max_length=100, verbose_name='支店名半角カナ')),
                ('branch_name_hiragana', models.CharField(blank=True, max_length=100, verbose_name='支店名ひらがな')),
                ('aiueo_row', models.CharField(blank=True, choices=[('あ', 'あ行'), ('か', 'か行'), ('さ', 'さ行'), ('た', 'た行'), ('な', 'な行'), ('は', 'は行'), ('ま', 'ま行'), ('や', 'や行'), ('ら', 'ら行'), ('わ', 'わ行')], db_index=True, help_text='頭文字の行（あ行、か行...）', max_length=2, verbose_name='あいうえお行')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '金融機関支店',
                'verbose_name_plural': '金融機関支店',
                'db_table': 'bank_branches',
                'ordering': ['sort_order', 'branch_name_hiragana'],
            },
        ),
        migrations.AddConstraint(
            model_name='banktype',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'type_code'), name='unique_bank_type_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'bank_code'), name='unique_bank_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bankbranch',
            constraint=models.UniqueConstraint(fields=('bank', 'branch_code'), name='unique_branch_per_bank'),
        ),
    ]
