# Generated by Django manual migration
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_bank_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='school',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='school_time_slots',
                to='schools.school',
                verbose_name='校舎'
            ),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(
                blank=True,
                choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '日曜日')],
                null=True,
                verbose_name='曜日'
            ),
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={
                'ordering': ['school', 'day_of_week', 'sort_order', 'start_time'],
                'verbose_name': 'T13_時間帯',
                'verbose_name_plural': 'T13_時間帯'
            },
        ),
    ]
