# Generated by Django 4.2.26 on 2025-12-13 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
        ("schools", "0016_add_timeslot_school_dayofweek"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarOperationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("ab_swap", "ABスワップ"),
                            ("set_closure", "休校設定"),
                            ("cancel_closure", "休校解除"),
                            ("lesson_type_change", "レッスンタイプ変更"),
                            ("schedule_change", "スケジュール変更"),
                            ("staff_absence", "スタッフ欠勤"),
                            ("native_absence", "外国人欠勤"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="操作種別",
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="対象日")),
                (
                    "operated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作日時"),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, max_length=100, verbose_name="変更前"),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, max_length=100, verbose_name="変更後"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="理由")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="メタデータ"
                    ),
                ),
            ],
            options={
                "verbose_name": "カレンダー操作ログ",
                "verbose_name_plural": "カレンダー操作ログ",
                "db_table": "calendar_operation_logs",
                "ordering": ["-operated_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="bank",
            name="unique_bank_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="bankbranch",
            name="unique_branch_per_bank",
        ),
        migrations.RemoveConstraint(
            model_name="banktype",
            name="unique_bank_type_per_tenant",
        ),
        # Note: Skipped AlterUniqueTogether for timeslot as the constraint doesn't exist in production
        # migrations.AlterUniqueTogether(
        #     name="timeslot",
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name="bank",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="bankbranch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="banktype",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterField(
            model_name="bankbranch",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
        migrations.AlterField(
            model_name="bankbranch",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterField(
            model_name="banktype",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
        migrations.AlterField(
            model_name="banktype",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bank",
            unique_together={("tenant_id", "bank_code")},
        ),
        migrations.AlterUniqueTogether(
            name="bankbranch",
            unique_together={("bank", "branch_code")},
        ),
        migrations.AlterUniqueTogether(
            name="banktype",
            unique_together={("tenant_id", "type_code")},
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="schools.brand",
                verbose_name="ブランド",
            ),
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="lesson_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="schools.lessoncalendar",
                verbose_name="開講カレンダー",
            ),
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="operated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_operations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作者",
            ),
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="schools.schoolschedule",
                verbose_name="スケジュール",
            ),
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AddField(
            model_name="calendaroperationlog",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
    ]
