# Generated by Django 4.2.26 on 2025-12-14 06:16
# NOTE: This migration was emptied because the unique_together constraint
# did not exist in the database (constraint already removed or never created)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_add_calendar_operation_log'),
    ]

    operations = [
        # No operations - constraint already handled
    ]
