# Generated by Django 4.2.26 on 2025-12-15 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("schools", "0018_add_discount_operation_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="例: 1001_SKAEC_A, 1003_AEC_P, Int_24",
                        max_length=50,
                        verbose_name="カレンダーコード",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="カレンダー名"
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("A", "Aパターン（外国人講師あり）"),
                            ("B", "Bパターン（日本人講師のみ）"),
                            ("P", "Pパターン（ペア）"),
                            ("Y", "Yパターン（インター）"),
                            ("other", "その他"),
                        ],
                        default="A",
                        max_length=10,
                        verbose_name="授業タイプ",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_masters",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T13m_カレンダーマスター",
                "verbose_name_plural": "T13m_カレンダーマスター",
                "db_table": "t13m_calendar_masters",
                "ordering": ["sort_order", "code"],
                "unique_together": {("tenant_id", "code")},
            },
        ),
        migrations.AddField(
            model_name="classschedule",
            name="calendar_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_slots",
                to="schools.calendarmaster",
                verbose_name="カレンダーマスター",
            ),
        ),
        migrations.AddField(
            model_name="lessoncalendar",
            name="calendar_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_calendars",
                to="schools.calendarmaster",
                verbose_name="カレンダーマスター",
            ),
        ),
        migrations.AddField(
            model_name="schoolschedule",
            name="calendar_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_schedules",
                to="schools.calendarmaster",
                verbose_name="カレンダーマスター",
            ),
        ),
    ]
