# Generated by Django 4.2.26 on 2025-12-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0019_add_calendar_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classschedule",
            name="calendar_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_schedules_t14c",
                to="schools.calendarmaster",
                verbose_name="カレンダーマスター",
            ),
        ),
    ]
