# Generated by Django 4.2.26 on 2025-12-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0020_fix_calendar_master_related_names"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together=set(),
        ),
    ]
