# Generated by Django 4.2.26 on 2026-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0022_add_first_fiscal_year_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandcategory",
            name="purchase_notes",
            field=models.TextField(blank=True, verbose_name="購入時注意書き"),
        ),
    ]
