# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="テナントID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="メール認証済み"),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "生徒"),
                            ("GUARDIAN", "保護者"),
                            ("TEACHER", "講師"),
                            ("STAFF", "スタッフ"),
                            ("ADMIN", "管理者"),
                        ],
                        default="STAFF",
                        max_length=20,
                        verbose_name="ユーザー種別",
                    ),
                ),
                (
                    "user_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="ユーザー番号",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="姓")),
                ("first_name", models.CharField(max_length=50, verbose_name="名")),
                (
                    "last_name_kana",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="姓（カナ）"
                    ),
                ),
                (
                    "first_name_kana",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="名（カナ）"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="表示名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="LINE ID"
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="プロフィール画像URL",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生年月日"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="性別"
                    ),
                ),
                (
                    "student_id",
                    models.UUIDField(blank=True, null=True, verbose_name="生徒ID"),
                ),
                (
                    "staff_id",
                    models.UUIDField(blank=True, null=True, verbose_name="スタッフID"),
                ),
                (
                    "primary_school_id",
                    models.UUIDField(blank=True, null=True, verbose_name="主校舎ID"),
                ),
                (
                    "primary_brand_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="主ブランドID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "一般ユーザー"),
                            ("TEACHER", "講師"),
                            ("SCHOOL_MANAGER", "校舎管理者"),
                            ("ADMIN", "管理者"),
                            ("SUPER_ADMIN", "システム管理者"),
                        ],
                        default="USER",
                        max_length=30,
                        verbose_name="ロール",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(blank=True, default=dict, verbose_name="権限"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="スタッフ権限"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終ログイン"
                    ),
                ),
                (
                    "failed_login_count",
                    models.IntegerField(default=0, verbose_name="ログイン失敗回数"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ロック解除日時"
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="パスワード変更日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "parent_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="親アカウント",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
                "db_table": "t16_users",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "user_type"],
                        name="t16_users_tenant__dc44e8_idx",
                    ),
                    models.Index(fields=["email"], name="t16_users_email_8c4681_idx"),
                ],
            },
        ),
    ]
