# Generated by Django 4.2.26 on 2025-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expectations",
            field=models.TextField(blank=True, null=True, verbose_name="期待すること"),
        ),
        migrations.AddField(
            model_name="user",
            name="interested_brands",
            field=models.JSONField(
                blank=True, default=list, verbose_name="興味のあるブランド"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nearest_school_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="最寄り校舎ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_source",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="流入経路"
            ),
        ),
    ]
