# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='会社ID'),
        ),
    ]
