# Generated by Django 4.2.27 on 2025-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', '一般ユーザー'), ('TEACHER', '講師'), ('SCHOOL_MANAGER', '校舎管理者'), ('ACCOUNTING', '経理'), ('ADMIN', '管理者'), ('SUPER_ADMIN', 'システム管理者')], default='USER', max_length=30, verbose_name='ロール'),
        ),
    ]
