# Generated by Django manual migration
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0012_merge_20251213_1427'),
        ('tenants', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        # PaymentProvider (決済代行会社マスタ)
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='例: ufj_factor, jaccs, chukyo_finance', max_length=30, verbose_name='識別コード')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('consignor_code', models.CharField(help_text='決済代行会社から付与された委託者コード', max_length=20, verbose_name='委託者コード')),
                ('default_bank_code', models.CharField(blank=True, help_text='エクスポート時のデフォルト銀行コード', max_length=4, verbose_name='デフォルト銀行コード')),
                ('file_encoding', models.CharField(default='shift_jis', help_text='CSVファイルのエンコーディング', max_length=20, verbose_name='ファイルエンコーディング')),
                ('closing_day', models.IntegerField(default=25, help_text='毎月の締日（1-31）', verbose_name='締日')),
                ('debit_day', models.IntegerField(default=27, help_text='毎月の引落日（1-31）', verbose_name='引落日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': '決済代行会社',
                'verbose_name_plural': '決済代行会社',
                'db_table': 'billing_payment_providers',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentprovider',
            constraint=models.UniqueConstraint(fields=['tenant_id', 'code'], name='unique_provider_code'),
        ),

        # BillingPeriod (請求期間/締日管理)
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='対象年')),
                ('month', models.IntegerField(verbose_name='対象月')),
                ('closing_date', models.DateField(help_text='この期間の実際の締日', verbose_name='締日')),
                ('is_closed', models.BooleanField(default=False, verbose_name='締め済み')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='締め日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='billing.paymentprovider', verbose_name='決済代行会社')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_billing_periods', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': '請求期間',
                'verbose_name_plural': '請求期間',
                'db_table': 'billing_periods',
                'ordering': ['-year', '-month', 'provider'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=['tenant_id', 'provider', 'year', 'month'], name='unique_billing_period'),
        ),

        # DebitExportBatch (引落データエクスポートバッチ)
        migrations.CreateModel(
            name='DebitExportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=30, verbose_name='バッチ番号')),
                ('export_date', models.DateTimeField(blank=True, null=True, verbose_name='エクスポート日時')),
                ('total_count', models.IntegerField(default=0, verbose_name='総件数')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='総金額')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功件数')),
                ('success_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='成功金額')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失敗件数')),
                ('failed_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='失敗金額')),
                ('result_imported_at', models.DateTimeField(blank=True, null=True, verbose_name='結果取込日時')),
                ('status', models.CharField(choices=[('draft', '作成中'), ('exported', 'エクスポート済'), ('result_imported', '結果取込済')], default='draft', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_batches', to='billing.paymentprovider', verbose_name='決済代行会社')),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_batches', to='billing.billingperiod', verbose_name='請求期間')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_debit_batches', to=settings.AUTH_USER_MODEL, verbose_name='エクスポート実行者')),
                ('result_imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_debit_batches', to=settings.AUTH_USER_MODEL, verbose_name='結果取込実行者')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': '引落エクスポートバッチ',
                'verbose_name_plural': '引落エクスポートバッチ',
                'db_table': 'billing_debit_export_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='debitexportbatch',
            constraint=models.UniqueConstraint(fields=['tenant_id', 'batch_no'], name='unique_batch_no'),
        ),

        # DebitExportLine (引落データエクスポート明細)
        migrations.CreateModel(
            name='DebitExportLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.BigIntegerField(db_index=True, default=0, editable=False, verbose_name='テナントID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.IntegerField(verbose_name='行番号')),
                ('bank_code', models.CharField(max_length=4, verbose_name='銀行コード')),
                ('branch_code', models.CharField(max_length=3, verbose_name='支店コード')),
                ('account_type', models.CharField(help_text='1:普通, 2:当座', max_length=1, verbose_name='預金種目')),
                ('account_number', models.CharField(max_length=8, verbose_name='口座番号')),
                ('account_holder_kana', models.CharField(max_length=100, verbose_name='口座名義（カナ）')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='引落金額')),
                ('customer_code', models.CharField(help_text='保護者番号など識別用コード', max_length=20, verbose_name='顧客番号')),
                ('result_code', models.CharField(blank=True, max_length=10, verbose_name='結果コード')),
                ('result_status', models.CharField(choices=[('pending', '未処理'), ('success', '成功'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='結果ステータス')),
                ('result_message', models.CharField(blank=True, max_length=200, verbose_name='結果メッセージ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.debitexportbatch', verbose_name='バッチ')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_export_lines', to='students.guardian', verbose_name='保護者')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_export_lines', to='billing.invoice', verbose_name='請求書')),
                ('direct_debit_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_lines', to='billing.directdebitresult', verbose_name='引落結果')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_lines', to='billing.payment', verbose_name='入金')),
                ('tenant_ref', models.ForeignKey(blank=True, db_column='tenant_ref_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': '引落エクスポート明細',
                'verbose_name_plural': '引落エクスポート明細',
                'db_table': 'billing_debit_export_lines',
                'ordering': ['batch', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='debitexportline',
            index=models.Index(fields=['batch', 'line_no'], name='billing_deb_batch_line_idx'),
        ),
        migrations.AddIndex(
            model_name='debitexportline',
            index=models.Index(fields=['guardian'], name='billing_deb_guardian_idx'),
        ),
        migrations.AddIndex(
            model_name='debitexportline',
            index=models.Index(fields=['result_status'], name='billing_deb_result_idx'),
        ),
    ]
