# Generated by Django 4.2.26 on 2025-12-14 06:16
# Modified: Removed AlterField for tenant_id since we'll handle type conversion with RunSQL

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('billing', '0004_fix_tenant_id_type'),
    ]

    operations = [
        # First, convert tenant_id columns from bigint to uuid for remaining tables
        migrations.RunSQL(
            sql="""
            -- BankTransfer
            ALTER TABLE billing_bank_transfers
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- CashManagement
            ALTER TABLE billing_cash_management
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- DirectDebitResult
            ALTER TABLE billing_direct_debit_results
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- GuardianBalance
            ALTER TABLE billing_guardian_balances
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- Invoice
            ALTER TABLE billing_invoices
            DROP CONSTRAINT IF EXISTS unique_invoice_no;

            ALTER TABLE billing_invoices
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- InvoiceLine
            ALTER TABLE billing_invoice_lines
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- MileTransaction
            ALTER TABLE billing_mile_transactions
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- OffsetLog
            ALTER TABLE billing_offset_logs
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- Payment
            ALTER TABLE billing_payments
            DROP CONSTRAINT IF EXISTS unique_payment_no;

            ALTER TABLE billing_payments
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- RefundRequest
            ALTER TABLE billing_refund_requests
            DROP CONSTRAINT IF EXISTS unique_refund_request_no;

            ALTER TABLE billing_refund_requests
            ALTER COLUMN tenant_id TYPE uuid USING (
                CASE
                    WHEN tenant_id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                    ELSE '00000000-0000-0000-0000-000000000000'::uuid
                END
            );

            -- Recreate unique constraints
            ALTER TABLE billing_invoices
            ADD CONSTRAINT unique_invoice_no UNIQUE (tenant_id, invoice_no);

            ALTER TABLE billing_payments
            ADD CONSTRAINT unique_payment_no UNIQUE (tenant_id, payment_no);

            ALTER TABLE billing_refund_requests
            ADD CONSTRAINT unique_refund_request_no UNIQUE (tenant_id, request_no);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # Index renames
        migrations.RunSQL(
            sql="""
            -- Safely rename indexes (drop old if exists, create new)
            DROP INDEX IF EXISTS billing_bt_date_idx;
            DROP INDEX IF EXISTS billing_bt_payer_idx;
            DROP INDEX IF EXISTS billing_bt_status_idx;
            DROP INDEX IF EXISTS billing_cash_guardian_idx;
            DROP INDEX IF EXISTS billing_cash_status_idx;
            DROP INDEX IF EXISTS billing_deb_batch_line_idx;
            DROP INDEX IF EXISTS billing_deb_guardian_idx;
            DROP INDEX IF EXISTS billing_deb_result_idx;
            DROP INDEX IF EXISTS billing_ddr_guardian_idx;
            DROP INDEX IF EXISTS billing_ddr_status_idx;
            DROP INDEX IF EXISTS billing_inv_guardia_idx;
            DROP INDEX IF EXISTS billing_inv_status_idx;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # Update unique_together
        migrations.AlterUniqueTogether(
            name='billingperiod',
            unique_together={('tenant_id', 'provider', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='debitexportbatch',
            unique_together={('tenant_id', 'batch_no')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentprovider',
            unique_together={('tenant_id', 'code')},
        ),
    ]
