# Generated by Django 4.2.26 on 2025-12-17 15:22
# Simplified migration - only creates MonthlyBillingDeadline model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0006_add_invoice_lock_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBillingDeadline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(verbose_name="対象年")),
                ("month", models.IntegerField(verbose_name="対象月")),
                (
                    "closing_day",
                    models.IntegerField(
                        default=25,
                        help_text="毎月この日を過ぎると、当月分の請求は編集不可になる",
                        verbose_name="締日",
                    ),
                ),
                (
                    "auto_close",
                    models.BooleanField(
                        default=True,
                        help_text="締日を過ぎたら自動的にロック状態にする",
                        verbose_name="自動締め",
                    ),
                ),
                (
                    "is_manually_closed",
                    models.BooleanField(
                        default=False,
                        help_text="締日前でも手動で締めることが可能",
                        verbose_name="手動締め済み",
                    ),
                ),
                (
                    "manually_closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="手動締め日時"
                    ),
                ),
                (
                    "is_reopened",
                    models.BooleanField(default=False, verbose_name="締め解除済み"),
                ),
                (
                    "reopened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="締め解除日時"
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(blank=True, verbose_name="締め解除理由"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "manually_closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manually_closed_deadlines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="手動締め実行者",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reopened_deadlines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="締め解除実行者",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "月次請求締切",
                "verbose_name_plural": "月次請求締切",
                "db_table": "billing_monthly_deadlines",
                "ordering": ["-year", "-month"],
                "unique_together": {("tenant_id", "year", "month")},
            },
        ),
    ]
