# Generated by Django 4.2.26 on 2025-12-17 15:47
# Simplified migration - only creates BankTransferImport model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
        ("billing", "0007_add_monthly_billing_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransferImport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(max_length=30, verbose_name="バッチ番号"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=200, verbose_name="ファイル名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        default="csv", max_length=20, verbose_name="ファイル形式"
                    ),
                ),
                ("total_count", models.IntegerField(default=0, verbose_name="総件数")),
                (
                    "matched_count",
                    models.IntegerField(default=0, verbose_name="照合済件数"),
                ),
                (
                    "unmatched_count",
                    models.IntegerField(default=0, verbose_name="未照合件数"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="エラー件数"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="総金額",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "処理中"),
                            ("completed", "完了"),
                            ("partial", "一部照合済"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="インポート日時"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確定日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_bank_transfer_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確定実行者",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transfer_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="インポート実行者",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "振込インポートバッチ",
                "verbose_name_plural": "振込インポートバッチ",
                "db_table": "billing_bank_transfer_imports",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AddIndex(
            model_name="banktransferimport",
            index=models.Index(fields=["batch_no"], name="billing_ban_batch_n_e8a3cd_idx"),
        ),
        migrations.AddIndex(
            model_name="banktransferimport",
            index=models.Index(fields=["status"], name="billing_ban_status_7e2d1e_idx"),
        ),
        migrations.AddIndex(
            model_name="banktransferimport",
            index=models.Index(fields=["-imported_at"], name="billing_ban_importe_d4f42c_idx"),
        ),
    ]
