# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_first_fiscal_year_free'),
        ('billing', '0011_banktransfer_guardian_no_hint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingperiod',
            name='unique_billing_period',
        ),
        migrations.RemoveConstraint(
            model_name='debitexportbatch',
            name='unique_batch_no',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_no',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_no',
        ),
        migrations.RemoveConstraint(
            model_name='paymentprovider',
            name='unique_provider_code',
        ),
        migrations.RemoveConstraint(
            model_name='refundrequest',
            name='unique_refund_request_no',
        ),
        # RenameIndex operations removed - indexes already exist with correct names
        migrations.AlterField(
            model_name='banktransfer',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='banktransferimport',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='banktransferimport',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='cashmanagement',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='cashmanagement',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='confirmedbilling',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='confirmedbilling',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='debitexportbatch',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='debitexportbatch',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='debitexportline',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='debitexportline',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='directdebitresult',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='directdebitresult',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='guardianbalance',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='guardianbalance',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='miletransaction',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='miletransaction',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='monthlybillingdeadline',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='monthlybillingdeadline',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='offsetlog',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='offsetlog',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant_id', 'invoice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant_id', 'payment_no')},
        ),
        migrations.AlterUniqueTogether(
            name='refundrequest',
            unique_together={('tenant_id', 'request_no')},
        ),
    ]
