# Generated by Django 4.2.27 on 2025-12-20 04:26
# Modified: 条件付きインデックスリネーム（存在しない場合はスキップ）

from django.db import migrations, connection


def index_exists(index_name):
    """インデックスが存在するかチェック"""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s",
                [index_name]
            )
        elif connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type='index' AND name = %s",
                [index_name]
            )
        else:
            return False
        return cursor.fetchone() is not None


def rename_index_if_exists(old_name, new_name, table_name):
    """インデックスが存在する場合のみリネーム"""
    if not index_exists(old_name):
        return  # 古いインデックスが存在しない場合はスキップ

    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
        elif connection.vendor == 'sqlite':
            # SQLiteはインデックスのリネームをサポートしないのでスキップ
            pass


def forwards(apps, schema_editor):
    """Forward migration: インデックスをリネーム"""
    renames = [
        ('billing_bt_date_idx', 'billing_ban_transfe_6aa1ad_idx', 'billing_banktransfer'),
        ('billing_bt_payer_idx', 'billing_ban_payer_n_7abd5f_idx', 'billing_banktransfer'),
        ('billing_bt_status_idx', 'billing_ban_status_03372a_idx', 'billing_banktransfer'),
        ('billing_ban_batch_n_e8a3cd_idx', 'billing_ban_batch_n_ada66b_idx', 'billing_banktransferimport'),
        ('billing_ban_status_7e2d1e_idx', 'billing_ban_status_7a3454_idx', 'billing_banktransferimport'),
        ('billing_ban_importe_d4f42c_idx', 'billing_ban_importe_df88e8_idx', 'billing_banktransferimport'),
        ('billing_cash_guardian_idx', 'billing_cas_guardia_c1492e_idx', 'billing_cashmanagement'),
        ('billing_cash_status_idx', 'billing_cas_status_9f85c9_idx', 'billing_cashmanagement'),
        ('t_confirmed_student_2c3c15_idx', 't_confirmed_student_1e1c7a_idx', 't_confirmed_billing'),
        ('t_confirmed_guardia_b7e9c4_idx', 't_confirmed_guardia_6846a0_idx', 't_confirmed_billing'),
        ('t_confirmed_status_8b5a47_idx', 't_confirmed_status_94e084_idx', 't_confirmed_billing'),
        ('t_confirmed_confirm_b2e2d3_idx', 't_confirmed_confirm_4ebf81_idx', 't_confirmed_billing'),
        ('billing_deb_batch_line_idx', 'billing_deb_batch_i_733483_idx', 'billing_debitexportline'),
        ('billing_deb_guardian_idx', 'billing_deb_guardia_8851d7_idx', 'billing_debitexportline'),
        ('billing_deb_result_idx', 'billing_deb_result__5b5ac7_idx', 'billing_debitexportline'),
        ('billing_ddr_guardian_idx', 'billing_dir_guardia_1ab11a_idx', 'billing_directdebitresult'),
        ('billing_ddr_status_idx', 'billing_dir_result__3cde47_idx', 'billing_directdebitresult'),
        ('billing_inv_guardia_idx', 'billing_inv_guardia_55744b_idx', 'billing_invoice'),
        ('billing_inv_status_idx', 'billing_inv_status_aefe38_idx', 'billing_invoice'),
    ]

    for old_name, new_name, table_name in renames:
        rename_index_if_exists(old_name, new_name, table_name)


def backwards(apps, schema_editor):
    """Backward migration: インデックスを元に戻す"""
    renames = [
        ('billing_ban_transfe_6aa1ad_idx', 'billing_bt_date_idx', 'billing_banktransfer'),
        ('billing_ban_payer_n_7abd5f_idx', 'billing_bt_payer_idx', 'billing_banktransfer'),
        ('billing_ban_status_03372a_idx', 'billing_bt_status_idx', 'billing_banktransfer'),
        ('billing_ban_batch_n_ada66b_idx', 'billing_ban_batch_n_e8a3cd_idx', 'billing_banktransferimport'),
        ('billing_ban_status_7a3454_idx', 'billing_ban_status_7e2d1e_idx', 'billing_banktransferimport'),
        ('billing_ban_importe_df88e8_idx', 'billing_ban_importe_d4f42c_idx', 'billing_banktransferimport'),
        ('billing_cas_guardia_c1492e_idx', 'billing_cash_guardian_idx', 'billing_cashmanagement'),
        ('billing_cas_status_9f85c9_idx', 'billing_cash_status_idx', 'billing_cashmanagement'),
        ('t_confirmed_student_1e1c7a_idx', 't_confirmed_student_2c3c15_idx', 't_confirmed_billing'),
        ('t_confirmed_guardia_6846a0_idx', 't_confirmed_guardia_b7e9c4_idx', 't_confirmed_billing'),
        ('t_confirmed_status_94e084_idx', 't_confirmed_status_8b5a47_idx', 't_confirmed_billing'),
        ('t_confirmed_confirm_4ebf81_idx', 't_confirmed_confirm_b2e2d3_idx', 't_confirmed_billing'),
        ('billing_deb_batch_i_733483_idx', 'billing_deb_batch_line_idx', 'billing_debitexportline'),
        ('billing_deb_guardia_8851d7_idx', 'billing_deb_guardian_idx', 'billing_debitexportline'),
        ('billing_deb_result__5b5ac7_idx', 'billing_deb_result_idx', 'billing_debitexportline'),
        ('billing_dir_guardia_1ab11a_idx', 'billing_ddr_guardian_idx', 'billing_directdebitresult'),
        ('billing_dir_result__3cde47_idx', 'billing_ddr_status_idx', 'billing_directdebitresult'),
        ('billing_inv_guardia_55744b_idx', 'billing_inv_guardia_idx', 'billing_invoice'),
        ('billing_inv_status_aefe38_idx', 'billing_inv_status_idx', 'billing_invoice'),
    ]

    for old_name, new_name, table_name in renames:
        rename_index_if_exists(old_name, new_name, table_name)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_billingperiod_unique_billing_period_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
