# Generated by Django 4.2.27 on 2025-12-20 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0013_rename_billing_bt_date_idx_billing_ban_transfe_6aa1ad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillingdeadline',
            name='is_under_review',
            field=models.BooleanField(default=False, help_text='経理が確認中。経理以外は編集不可', verbose_name='確認中'),
        ),
        migrations.AddField(
            model_name='monthlybillingdeadline',
            name='under_review_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認開始日時'),
        ),
        migrations.AddField(
            model_name='monthlybillingdeadline',
            name='under_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_started_deadlines', to=settings.AUTH_USER_MODEL, verbose_name='確認開始者'),
        ),
    ]
