# Generated by Django 4.2.27 on 2025-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_under_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianbalance',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='プラス=預り金（過払い）、マイナス=不足金（未払い繰越）', max_digits=12, verbose_name='残高'),
        ),
    ]
