# Generated by Django 4.2.27 on 2025-12-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_guardianbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedbilling',
            name='billing_no',
            field=models.CharField(blank=True, db_index=True, help_text='例: CB202501-0001', max_length=20, verbose_name='請求番号'),
        ),
    ]
