# Generated by Django 4.2.27 on 2025-12-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_billing_no_to_confirmed_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedbilling',
            options={'ordering': ['guardian__last_name', 'guardian__first_name', 'student__last_name', 'student__first_name', 'billing_no'], 'verbose_name': '請求確定', 'verbose_name_plural': '請求確定'},
        ),
    ]
