# Generated by Django 4.2.27 on 2025-12-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_confirmedbilling_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedbilling',
            name='brand_withdrawal_dates',
            field=models.JSONField(blank=True, default=dict, help_text='ブランドごとの退会日 {brand_id: "YYYY-MM-DD"}', verbose_name='ブランド退会日'),
        ),
        migrations.AddField(
            model_name='confirmedbilling',
            name='withdrawal_date',
            field=models.DateField(blank=True, help_text='生徒の退会日', null=True, verbose_name='全退会日'),
        ),
    ]
