# Generated by Django 4.2.27 on 2025-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_add_withdrawal_dates_to_confirmed_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedbilling',
            name='return_date',
            field=models.DateField(blank=True, help_text='生徒の復会日', null=True, verbose_name='復会日'),
        ),
        migrations.AddField(
            model_name='confirmedbilling',
            name='suspension_date',
            field=models.DateField(blank=True, help_text='生徒の休会日', null=True, verbose_name='休会日'),
        ),
    ]
