# Generated by Django 4.2.26 on 2025-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_add_suspension_return_date_to_confirmed_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmedbilling",
            name="adjustment_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="過不足金（プラス=追加請求、マイナス=返金/相殺）",
                max_digits=12,
                verbose_name="過不足金",
            ),
        ),
        migrations.AddField(
            model_name="confirmedbilling",
            name="adjustment_note",
            field=models.TextField(
                blank=True, help_text="過不足金の詳細説明", verbose_name="過不足金備考"
            ),
        ),
    ]
