# Generated by Django 4.2.27 on 2025-12-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_add_adjustment_to_confirmed_billing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banktransfer',
            new_name='billing_ban_transfe_6aa1ad_idx',
            old_name='billing_bt_date_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransfer',
            new_name='billing_ban_payer_n_7abd5f_idx',
            old_name='billing_bt_payer_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransfer',
            new_name='billing_ban_status_03372a_idx',
            old_name='billing_bt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransferimport',
            new_name='billing_ban_batch_n_ada66b_idx',
            old_name='billing_ban_batch_n_e8a3cd_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransferimport',
            new_name='billing_ban_status_7a3454_idx',
            old_name='billing_ban_status_7e2d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransferimport',
            new_name='billing_ban_importe_df88e8_idx',
            old_name='billing_ban_importe_d4f42c_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmanagement',
            new_name='billing_cas_guardia_c1492e_idx',
            old_name='billing_cash_guardian_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmanagement',
            new_name='billing_cas_status_9f85c9_idx',
            old_name='billing_cash_status_idx',
        ),
        migrations.RenameIndex(
            model_name='confirmedbilling',
            new_name='t_confirmed_student_1e1c7a_idx',
            old_name='t_confirmed_student_2c3c15_idx',
        ),
        migrations.RenameIndex(
            model_name='confirmedbilling',
            new_name='t_confirmed_guardia_6846a0_idx',
            old_name='t_confirmed_guardia_b7e9c4_idx',
        ),
        migrations.RenameIndex(
            model_name='confirmedbilling',
            new_name='t_confirmed_status_94e084_idx',
            old_name='t_confirmed_status_8b5a47_idx',
        ),
        migrations.RenameIndex(
            model_name='confirmedbilling',
            new_name='t_confirmed_confirm_4ebf81_idx',
            old_name='t_confirmed_confirm_b2e2d3_idx',
        ),
        migrations.RenameIndex(
            model_name='debitexportline',
            new_name='billing_deb_batch_i_733483_idx',
            old_name='billing_deb_batch_line_idx',
        ),
        migrations.RenameIndex(
            model_name='debitexportline',
            new_name='billing_deb_guardia_8851d7_idx',
            old_name='billing_deb_guardian_idx',
        ),
        migrations.RenameIndex(
            model_name='debitexportline',
            new_name='billing_deb_result__5b5ac7_idx',
            old_name='billing_deb_result_idx',
        ),
        migrations.RenameIndex(
            model_name='directdebitresult',
            new_name='billing_dir_guardia_1ab11a_idx',
            old_name='billing_ddr_guardian_idx',
        ),
        migrations.RenameIndex(
            model_name='directdebitresult',
            new_name='billing_dir_result__3cde47_idx',
            old_name='billing_ddr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_guardia_55744b_idx',
            old_name='billing_inv_guardia_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_status_aefe38_idx',
            old_name='billing_inv_status_idx',
        ),
    ]
