# Generated by Django 4.2.27 on 2025-12-25 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_add_permission_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'テンプレートカテゴリ',
                'verbose_name_plural': 'テンプレートカテゴリ',
                'db_table': 't32_template_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.manualcategory', verbose_name='親カテゴリ')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'マニュアルカテゴリ',
                'verbose_name_plural': 'マニュアルカテゴリ',
                'db_table': 't30_manual_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='スラッグ')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, help_text='検索用の概要', verbose_name='概要')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='タグ')),
                ('external_url', models.URLField(blank=True, help_text='Google Docsなどの外部リンク', verbose_name='外部リンク')),
                ('view_count', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='ピン留め')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_manuals', to='tenants.employee', verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='knowledge.manualcategory', verbose_name='カテゴリ')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'マニュアル',
                'verbose_name_plural': 'マニュアル',
                'db_table': 't31_manuals',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('template_type', models.CharField(choices=[('chat', 'チャット返信'), ('email', 'メール'), ('sms', 'SMS'), ('notification', '通知')], default='chat', max_length=20, verbose_name='テンプレート種別')),
                ('scene', models.CharField(blank=True, help_text='例: 入会申請後の返信', max_length=200, verbose_name='使用場面')),
                ('subject', models.CharField(blank=True, help_text='メール用', max_length=200, verbose_name='件名')),
                ('content', models.TextField(verbose_name='本文')),
                ('variables', models.JSONField(blank=True, default=list, help_text='使用可能な変数 例: ["保護者名", "生徒名", "校舎名"]', verbose_name='変数')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='タグ')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用回数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, help_text='同じ場面でのデフォルトテンプレート', verbose_name='デフォルト')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='knowledge.templatecategory', verbose_name='カテゴリ')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'チャットテンプレート',
                'verbose_name_plural': 'チャットテンプレート',
                'db_table': 't33_chat_templates',
                'ordering': ['-is_default', '-use_count', 'title'],
            },
        ),
    ]
