# Generated by Django 4.2.27 on 2025-12-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='cover_image',
            field=models.URLField(blank=True, help_text='サムネイル用の画像URL', verbose_name='カバー画像'),
        ),
        migrations.AddField(
            model_name='manual',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='添付画像のURL一覧 [{"url": "...", "alt": "..."}]', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='content',
            field=models.TextField(help_text='Markdown形式で記述可能', verbose_name='内容'),
        ),
    ]
