# Generated by Django 4.2.27 on 2025-12-08 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_code",
                    models.CharField(max_length=20, verbose_name="カテゴリコード"),
                ),
                (
                    "category_name",
                    models.CharField(max_length=50, verbose_name="カテゴリ名"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="アイコン"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="カラー"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="並び順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "作業カテゴリ",
                "verbose_name_plural": "作業カテゴリ",
                "db_table": "task_categories",
                "ordering": ["sort_order", "category_code"],
                "unique_together": {("tenant_id", "category_code")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "問い合わせ"),
                            ("request", "依頼"),
                            ("trouble", "トラブル"),
                            ("follow_up", "フォローアップ"),
                            ("guardian_registration", "保護者登録"),
                            ("student_registration", "生徒登録"),
                            ("chat", "チャット対応"),
                            ("trial_registration", "体験登録"),
                            ("enrollment", "入会申請"),
                            ("withdrawal", "退会申請"),
                            ("contract_change", "契約変更"),
                            ("other", "その他"),
                        ],
                        default="inquiry",
                        max_length=50,
                        verbose_name="種別",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("in_progress", "対応中"),
                            ("waiting", "保留"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "通常"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "assigned_to_id",
                    models.UUIDField(
                        blank=True,
                        db_column="assigned_to_id",
                        null=True,
                        verbose_name="担当者ID",
                    ),
                ),
                (
                    "created_by_id",
                    models.UUIDField(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        verbose_name="作成者ID",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="期限日"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=50, verbose_name="参照元種別"),
                ),
                (
                    "source_id",
                    models.UUIDField(blank=True, null=True, verbose_name="参照元ID"),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="参照元URL"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="メタデータ"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        db_column="brand_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.taskcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        db_column="guardian_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="students.guardian",
                        verbose_name="保護者",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        db_column="school_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="students.student",
                        verbose_name="生徒",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業",
                "verbose_name_plural": "作業一覧",
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(verbose_name="コメント")),
                (
                    "commented_by_id",
                    models.UUIDField(
                        blank=True,
                        db_column="commented_by_id",
                        null=True,
                        verbose_name="コメント者ID",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="内部メモは顧客に表示されません",
                        verbose_name="内部メモ",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_column="task_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                        verbose_name="作業",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業コメント",
                "verbose_name_plural": "作業コメント",
                "db_table": "task_comments",
                "ordering": ["created_at"],
            },
        ),
    ]
