# Generated by Django 4.2.27 on 2025-12-17 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('tasks', '0002_create_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='テナント'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='テナント'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='テナント'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('inquiry', '問い合わせ'), ('request', '依頼'), ('trouble', 'トラブル'), ('follow_up', 'フォローアップ'), ('guardian_registration', '保護者登録'), ('student_registration', '生徒登録'), ('chat', 'チャット対応'), ('trial_registration', '体験登録'), ('enrollment', '入会申請'), ('withdrawal', '退会申請'), ('suspension', '休会申請'), ('contract_change', '契約変更'), ('debit_failure', '引落失敗'), ('refund_request', '返金申請'), ('bank_account_request', '口座申請'), ('other', 'その他')], default='inquiry', max_length=50, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
