# Generated by Django 4.2.27 on 2025-12-08 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[
                            ("parent", "親会社"),
                            ("child", "子会社"),
                            ("standalone", "単独"),
                        ],
                        default="standalone",
                        max_length=20,
                        verbose_name="テナント種別",
                    ),
                ),
                (
                    "tenant_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="テナントコード"
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(max_length=100, verbose_name="テナント名"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="連絡先メール",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="連絡先電話番号",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="設定"),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="機能フラグ"
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FREE", "フリー"),
                            ("STANDARD", "スタンダード"),
                            ("PROFESSIONAL", "プロフェッショナル"),
                            ("ENTERPRISE", "エンタープライズ"),
                        ],
                        default="STANDARD",
                        max_length=30,
                        verbose_name="プラン",
                    ),
                ),
                (
                    "max_schools",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大校舎数"
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大ユーザー数"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tenants.tenant",
                        verbose_name="親テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "テナント",
                "verbose_name_plural": "テナント",
                "db_table": "tenants",
                "ordering": ["tenant_code"],
            },
        ),
    ]
