# Generated by Django 4.2.26 on 2025-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["tenant_code"],
                "verbose_name": "会社",
                "verbose_name_plural": "会社",
            },
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="会社ID",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tenants.tenant",
                verbose_name="親会社",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="会社コード"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_name",
            field=models.CharField(max_length=100, verbose_name="会社名"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[
                    ("parent", "親会社"),
                    ("child", "子会社"),
                    ("standalone", "単独"),
                ],
                default="standalone",
                max_length=20,
                verbose_name="会社種別",
            ),
        ),
    ]
