# Generated by Django 4.2.27 on 2025-12-23 08:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_first_fiscal_year_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='社員番号')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='役職')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='採用日')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='解雇日')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('nationality', models.CharField(blank=True, default='日本', max_length=50, verbose_name='国籍')),
                ('discount_flag', models.BooleanField(default=False, verbose_name='社員割引フラグ')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='社員割引額')),
                ('discount_unit', models.CharField(choices=[('%', '%'), ('yen', '円')], default='%', max_length=10, verbose_name='社員割引額単位')),
                ('discount_category_name', models.CharField(blank=True, max_length=50, verbose_name='社員割引請求カテゴリー名')),
                ('discount_category_code', models.IntegerField(default=0, verbose_name='社員割引請求カテゴリー区分')),
                ('ozaworks_registered', models.BooleanField(default=False, verbose_name='OZAWorks登録')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='students.guardian', verbose_name='保護者')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'T19_社員',
                'verbose_name_plural': 'T19_社員',
                'db_table': 't19_employees',
                'ordering': ['department', 'last_name', 'first_name'],
            },
        ),
    ]
