# Generated by Django 4.2.27 on 2025-12-23 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_employee'),
    ]

    operations = [
        # 1. まず既存のpositionカラムをposition_textにリネーム
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='position_text',
        ),
        # 2. Positionモデルを作成
        migrations.CreateModel(
            name='Position',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_code', models.CharField(blank=True, max_length=20, verbose_name='役職コード')),
                ('position_name', models.CharField(max_length=50, verbose_name='役職名')),
                ('rank', models.IntegerField(default=0, help_text='数字が大きいほど上位', verbose_name='ランク')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': '役職',
                'verbose_name_plural': '役職',
                'db_table': 't20_positions',
                'ordering': ['-rank', 'position_name'],
            },
        ),
        # 3. 新しいposition ForeignKeyを追加
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tenants.position', verbose_name='役職'),
        ),
    ]
