# Generated by Django 4.2.27 on 2025-12-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='employees', to='schools.brand', verbose_name='対応ブランド'),
        ),
        migrations.AddField(
            model_name='employee',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='employees', to='schools.school', verbose_name='対応校舎'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_text',
            field=models.CharField(blank=True, help_text='マスタ未登録時の役職名', max_length=50, verbose_name='役職（テキスト）'),
        ),
    ]
