# Generated by Django 4.2.27 on 2025-12-23 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_employee_schools_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(help_text='例: 1000, 2000, 10010', max_length=20, unique=True, verbose_name='機能コード')),
                ('feature_name', models.CharField(max_length=100, verbose_name='機能名')),
                ('parent_code', models.CharField(blank=True, help_text='サブ機能の場合、親の機能コード', max_length=20, verbose_name='親機能コード')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': '機能マスタ',
                'verbose_name_plural': '機能マスタ',
                'db_table': 't21_feature_masters',
                'ordering': ['display_order', 'feature_code'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='brand_restriction',
            field=models.BooleanField(default=False, help_text='ONの場合、所属ブランドのみ閲覧可能', verbose_name='ブランド制限'),
        ),
        migrations.AddField(
            model_name='position',
            name='bulk_email_restriction',
            field=models.BooleanField(default=False, help_text='ONの場合、一括送信不可', verbose_name='メール一括送信制限'),
        ),
        migrations.AddField(
            model_name='position',
            name='email_approval_required',
            field=models.BooleanField(default=False, help_text='ONの場合、メール送信に上長承認が必要', verbose_name='メール上長承認必要'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_accounting',
            field=models.BooleanField(default=False, help_text='経理系機能へのアクセス権限', verbose_name='経理権限'),
        ),
        migrations.AddField(
            model_name='position',
            name='school_restriction',
            field=models.BooleanField(default=False, help_text='ONの場合、所属校舎のみ閲覧可能', verbose_name='校舎制限'),
        ),
        migrations.CreateModel(
            name='PositionPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_permission', models.BooleanField(default=False, verbose_name='権限あり')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_permissions', to='tenants.featuremaster', verbose_name='機能')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenants.position', verbose_name='役職')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': '役職権限',
                'verbose_name_plural': '役職権限',
                'db_table': 't22_position_permissions',
                'ordering': ['position__rank', 'feature__display_order'],
                'unique_together': {('tenant_ref', 'position', 'feature')},
            },
        ),
    ]
