# Generated by Django 4.2.27 on 2025-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_permission_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuremaster',
            name='feature_code',
            field=models.CharField(db_index=True, help_text='例: 1000, 2000, 10010', max_length=20, verbose_name='機能コード'),
        ),
        migrations.AlterUniqueTogether(
            name='featuremaster',
            unique_together={('tenant_ref', 'feature_code')},
        ),
    ]
