# Generated by Django 4.2.27 on 2026-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_featuremaster_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='プロフィール画像URL'),
        ),
    ]
