# Generated by Django 4.2.27 on 2026-01-07 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_profile_image_url_to_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('members', models.ManyToManyField(blank=True, related_name='employee_groups', to='tenants.employee', verbose_name='メンバー')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': '社員グループ',
                'verbose_name_plural': '社員グループ',
                'db_table': 't19_employee_groups',
                'ordering': ['name'],
            },
        ),
    ]
