# Generated by Django 4.2.27 on 2026-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_employeegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='employee',
            name='commuting_method',
            field=models.CharField(blank=True, help_text='train/car/both', max_length=20, verbose_name='通勤方法'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nearest_station',
            field=models.CharField(blank=True, max_length=100, verbose_name='最寄駅'),
        ),
    ]
