# Generated by Django 4.2.27 on 2026-01-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_add_employee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approval_status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='承認ステータス'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='却下日時'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rejected_reason',
            field=models.TextField(blank=True, verbose_name='却下理由'),
        ),
    ]
