# Generated by Django 4.2.27 on 2025-12-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_tenant_no",
        ),
        migrations.AddField(
            model_name="guardian",
            name="account_holder",
            field=models.CharField(blank=True, max_length=100, verbose_name="口座名義"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="account_holder_kana",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="口座名義（カナ）"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="account_number",
            field=models.CharField(blank=True, max_length=8, verbose_name="口座番号"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ordinary", "普通"),
                    ("current", "当座"),
                    ("savings", "貯蓄"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="口座種別",
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="bank_code",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="金融機関コード"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="金融機関名"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="branch_code",
            field=models.CharField(blank=True, max_length=3, verbose_name="支店コード"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="branch_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="支店名"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="payment_registered",
            field=models.BooleanField(default=False, verbose_name="支払い方法登録済み"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="payment_registered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="支払い方法登録日時"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="withdrawal_day",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="引き落とし日"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("tenant_id", "student_no")},
        ),
    ]
