# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザーアカウント",
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guardian_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザーアカウント",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentguardian",
            unique_together={("student", "guardian")},
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("tenant_id", "student_no")},
        ),
    ]
