# Generated by Django 4.2.26 on 2025-12-02 14:10
# Modified: Removed duplicate operations (all fields/constraints already exist in 0001_initial)

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        # All operations removed - user fields and unique_together
        # are already defined in 0001_initial.py
    ]
