# Generated by Django 4.2.27 on 2025-12-08 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_add_lesson_calendar_csv_fields"),
        ("students", "0002_add_payment_fields_to_guardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialBooking",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trial_date", models.DateField(verbose_name="体験日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "予約待ち"),
                            ("confirmed", "確定"),
                            ("cancelled", "キャンセル"),
                            ("completed", "完了"),
                            ("no_show", "無断欠席"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確定日時"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="キャンセル日時"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="キャンセル理由"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_bookings",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_bookings",
                        to="students.guardian",
                        verbose_name="保護者",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_bookings",
                        to="schools.schoolschedule",
                        verbose_name="スケジュール枠",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_bookings",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_bookings",
                        to="students.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_bookings",
                        to="schools.timeslot",
                        verbose_name="時間帯",
                    ),
                ),
            ],
            options={
                "verbose_name": "T3_体験予約",
                "verbose_name_plural": "T3_体験予約",
                "db_table": "t03_trial_bookings",
                "ordering": ["trial_date", "created_at"],
                "unique_together": {("student", "trial_date", "schedule")},
            },
        ),
    ]
