# Generated by Django 4.2.27 on 2025-12-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("students", "0003_add_trial_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialbooking",
            name="task_id_ref",
            field=models.UUIDField(blank=True, null=True, verbose_name="関連タスクID"),
        ),
        migrations.AddField(
            model_name="trialbooking",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
    ]
