# Generated by Django 4.2.27 on 2025-12-05 07:57
# Modified: Removed duplicate field additions (fields already exist in 0001_initial)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("students", "0003_add_tenant_ref"),
    ]

    operations = [
        # All fields (expectations, interested_brands, nearest_school, referral_source)
        # are already defined in 0001_initial.py, so no operations needed here
    ]
