# Generated by Django 4.2.27 on 2025-12-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("students", "0003_add_tenant_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="expectations",
            field=models.TextField(blank=True, verbose_name="期待・要望"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="interested_brands",
            field=models.JSONField(
                blank=True, default=list, verbose_name="興味のあるブランド"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="nearest_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nearby_guardians",
                to="schools.school",
                verbose_name="最寄り校舎",
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="referral_source",
            field=models.CharField(blank=True, max_length=50, verbose_name="紹介元"),
        ),
    ]
