# Generated by Django 4.2.27 on 2025-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_registration_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="生徒番号"),
        ),
    ]
