# Generated by Django 4.2.26 on 2025-12-12 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_add_student_enrollment"),
        ("schools", "0013_add_grade_to_class_schedule"),
        ("tenants", "0001_initial"),
        ("contracts", "0019_add_monthly_prices_to_product"),
        ("students", "0004_add_task_id_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceTicket",
            fields=[],
            options={
                "verbose_name": "欠席・振替チケット",
                "verbose_name_plural": "欠席・振替チケット",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lessons.absenceticket",),
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0:月曜 〜 6:日曜",
                        null=True,
                        verbose_name="曜日",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="終了時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "体験"),
                            ("enrolled", "入会中"),
                            ("suspended", "休会中"),
                            ("withdrawn", "退会"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("new", "新規入会"),
                            ("trial", "体験"),
                            ("class_change", "クラス変更"),
                            ("school_change", "校舎変更"),
                            ("schedule_change", "曜日・時間変更"),
                            ("suspend", "休会"),
                            ("resume", "復会"),
                            ("withdraw", "退会"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="変更種別",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="適用開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="メタデータ"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments_history",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "class_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_enrollments",
                        to="schools.classschedule",
                        verbose_name="クラススケジュール",
                    ),
                ),
                (
                    "previous_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_enrollment",
                        to="students.studentenrollment",
                        verbose_name="前の受講記録",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments_history",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "student_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="contracts.studentitem",
                        verbose_name="購入明細",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_enrollments",
                        to="contracts.ticket",
                        verbose_name="チケット",
                    ),
                ),
            ],
            options={
                "verbose_name": "T12_生徒受講履歴",
                "verbose_name_plural": "T12_生徒受講履歴",
                "db_table": "t12_student_enrollments",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "end_date"],
                        name="t12_student_student_1b9a3f_idx",
                    ),
                    models.Index(
                        fields=["school", "brand"],
                        name="t12_student_school__578aee_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="t12_student_effecti_2603c5_idx"
                    ),
                ],
            },
        ),
    ]
