# Generated by Django 4.2.26 on 2025-12-12 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("schools", "0013_add_grade_to_class_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0005_add_student_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("withdrawal_date", models.DateField(verbose_name="退会希望日")),
                (
                    "last_lesson_date",
                    models.DateField(blank=True, null=True, verbose_name="最終授業日"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("moving", "転居"),
                            ("school_change", "学校変更"),
                            ("graduation", "卒業"),
                            ("schedule", "スケジュール都合"),
                            ("financial", "経済的理由"),
                            ("satisfaction", "満足度"),
                            ("other_school", "他塾への変更"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="退会理由",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="理由詳細"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="返金額",
                    ),
                ),
                (
                    "refund_calculated",
                    models.BooleanField(default=False, verbose_name="返金額計算済"),
                ),
                (
                    "remaining_tickets",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="残チケット数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認済"),
                            ("rejected", "却下"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="処理日時"
                    ),
                ),
                (
                    "process_notes",
                    models.TextField(blank=True, verbose_name="処理メモ"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="処理者",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="students.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T14_退会申請",
                "verbose_name_plural": "T14_退会申請",
                "db_table": "t14_withdrawal_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SuspensionRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suspend_from", models.DateField(verbose_name="休会開始日")),
                (
                    "suspend_until",
                    models.DateField(
                        blank=True,
                        help_text="未定の場合は空欄",
                        null=True,
                        verbose_name="休会終了予定日",
                    ),
                ),
                (
                    "keep_seat",
                    models.BooleanField(
                        default=False,
                        help_text="休会中も座席を確保する",
                        verbose_name="座席保持",
                    ),
                ),
                (
                    "monthly_fee_during_suspension",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="座席保持の場合の月会費",
                        max_digits=10,
                        null=True,
                        verbose_name="休会中月会費",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("travel", "旅行・帰省"),
                            ("illness", "病気・怪我"),
                            ("exam", "受験準備"),
                            ("schedule", "スケジュール都合"),
                            ("financial", "経済的理由"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="休会理由",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="理由詳細"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認済"),
                            ("rejected", "却下"),
                            ("cancelled", "取消"),
                            ("resumed", "復会済"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="処理日時"
                    ),
                ),
                (
                    "process_notes",
                    models.TextField(blank=True, verbose_name="処理メモ"),
                ),
                (
                    "resumed_at",
                    models.DateField(blank=True, null=True, verbose_name="復会日"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspension_requests",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_suspension_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="処理者",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspension_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
                (
                    "resumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resumed_suspension_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="復会処理者",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspension_requests",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspension_requests",
                        to="students.student",
                        verbose_name="生徒",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T13_休会申請",
                "verbose_name_plural": "T13_休会申請",
                "db_table": "t13_suspension_requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
