# Generated by Django 4.2.27 on 2025-12-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("students", "0005_auto_generate_student_guardian_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade_text",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="学年（テキスト）"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="schools.grade",
                verbose_name="学年マスタ",
            ),
        ),
    ]
