# Generated by Django 4.2.27 on 2025-12-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_add_grade_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="students.guardian",
                verbose_name="主保護者",
            ),
        ),
    ]
