# Generated by Django 4.2.27 on 2025-12-05 21:50
# Modified: Removed duplicate field addition (guardian already exists in 0001_initial)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_add_grade_text"),
    ]

    operations = [
        # guardian field is already defined in 0001_initial.py, so no operation needed
    ]
