# Generated by Django 4.2.27 on 2025-12-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_add_guardian_to_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="registered_date",
            field=models.DateField(blank=True, null=True, verbose_name="登録日"),
        ),
        migrations.AddField(
            model_name="student",
            name="suspended_date",
            field=models.DateField(blank=True, null=True, verbose_name="休会日"),
        ),
        migrations.AddField(
            model_name="student",
            name="trial_date",
            field=models.DateField(blank=True, null=True, verbose_name="体験日"),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(blank=True, null=True, verbose_name="入会日"),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "登録のみ"),
                    ("trial", "体験"),
                    ("enrolled", "入会"),
                    ("suspended", "休会"),
                    ("withdrawn", "退会"),
                ],
                default="registered",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="withdrawal_date",
            field=models.DateField(blank=True, null=True, verbose_name="退会日"),
        ),
        migrations.AlterField(
            model_name="student",
            name="withdrawal_reason",
            field=models.TextField(blank=True, verbose_name="退会理由"),
        ),
    ]
