# Generated by Django 4.2.27 on 2025-12-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("students", "0008_update_status_choices_and_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="brands",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                to="schools.brand",
                verbose_name="所属ブランド",
            ),
        ),
    ]
