# Generated by Django 4.2.27 on 2025-12-06 01:49
# Modified: Removed duplicate AddField (brands already exists in 0001_initial)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("students", "0008_update_status_choices_and_dates"),
    ]

    operations = [
        # brands field already exists in 0001_initial.py
    ]
