# Generated by Django 4.2.27 on 2025-12-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
        ("students", "0009_add_brands_many_to_many"),
    ]

    operations = []
