# Generated by Django 4.2.26 on 2025-12-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_add_bank_account_models"),
        ("students", "0011_add_fs_discount_models"),
    ]

    operations = []
