# Generated by Django 4.2.26 on 2025-12-14 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0005_add_discount_operation_log"),
        ("students", "0011_add_fs_discount_models"),
        ("students", "0007_add_bank_account_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendshipRegistration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("accepted", "承認済"),
                            ("rejected", "拒否"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "friend_code",
                    models.CharField(
                        blank=True,
                        help_text="紹介時に使用するコード",
                        max_length=20,
                        verbose_name="友達コード",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "T17_友達登録",
                "verbose_name_plural": "T17_友達登録",
                "db_table": "t17_friendship_registrations",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "ordering": ["-is_primary", "-created_at"],
                "verbose_name": "T15_銀行口座",
                "verbose_name_plural": "T15_銀行口座",
            },
        ),
        migrations.AlterModelOptions(
            name="bankaccountchangerequest",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "T16_銀行口座変更申請",
                "verbose_name_plural": "T16_銀行口座変更申請",
            },
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="notes",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="bankaccountchangerequest",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="bankaccountchangerequest",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="first_name_roman",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="名（ローマ字）"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="last_name_roman",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="姓（ローマ字）"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="old_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="旧システムID"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="workplace2",
            field=models.CharField(blank=True, max_length=100, verbose_name="勤務先2"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="workplace_phone2",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="勤務先2電話番号"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="address1",
            field=models.CharField(blank=True, max_length=100, verbose_name="住所1"),
        ),
        migrations.AddField(
            model_name="student",
            name="address2",
            field=models.CharField(blank=True, max_length=100, verbose_name="住所2"),
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="市区町村"),
        ),
        migrations.AddField(
            model_name="student",
            name="contract_status",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="契約ステータス"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name_roman",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="名（ローマ字）"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name_roman",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="姓（ローマ字）"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ニックネーム"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="old_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="旧システムID"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone2",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号2"),
        ),
        migrations.AddField(
            model_name="student",
            name="postal_code",
            field=models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
        ),
        migrations.AddField(
            model_name="student",
            name="prefecture",
            field=models.CharField(blank=True, max_length=10, verbose_name="都道府県"),
        ),
        migrations.AddField(
            model_name="student",
            name="referrer_old_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="紹介者旧ID"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(max_length=4, verbose_name="金融機関コード"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="branch_code",
            field=models.CharField(max_length=3, verbose_name="支店コード"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ordinary", "普通"),
                    ("current", "当座"),
                    ("savings", "貯蓄"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="口座種別",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_bank_account_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="処理者",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "申請中"),
                    ("approved", "承認済"),
                    ("rejected", "却下"),
                    ("cancelled", "取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
        migrations.AlterModelTable(
            name="bankaccount",
            table="t15_bank_accounts",
        ),
        migrations.AlterModelTable(
            name="bankaccountchangerequest",
            table="t16_bank_account_requests",
        ),
        migrations.CreateModel(
            name="FSDiscount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "割合割引"),
                            ("fixed", "固定額割引"),
                            ("months_free", "月謝無料"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="割引タイプ",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="割引値",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有効"),
                            ("used", "使用済"),
                            ("expired", "期限切れ"),
                            ("cancelled", "取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="有効開始日")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="有効期限"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用日時"
                    ),
                ),
                (
                    "applied_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="適用額",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "friendship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="students.friendshipregistration",
                        verbose_name="友達登録",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fs_discounts",
                        to="students.guardian",
                        verbose_name="保護者",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "used_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fs_discounts",
                        to="billing.invoice",
                        verbose_name="使用請求書",
                    ),
                ),
            ],
            options={
                "verbose_name": "T18_FS割引",
                "verbose_name_plural": "T18_FS割引",
                "db_table": "t18_fs_discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="friendshipregistration",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_sent",
                to="students.guardian",
                verbose_name="申請者",
            ),
        ),
        migrations.AddField(
            model_name="friendshipregistration",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_received",
                to="students.guardian",
                verbose_name="対象者",
            ),
        ),
        migrations.AddField(
            model_name="friendshipregistration",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendshipregistration",
            unique_together={("requester", "target")},
        ),
    ]
