# Generated by Django 4.2.26 on 2025-12-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_add_discount_operation_log"),
        ("students", "0013_add_discount_operation_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentschool",
            name="class_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_school_enrollments",
                to="schools.classschedule",
                verbose_name="クラススケジュール",
            ),
        ),
        migrations.AddField(
            model_name="studentschool",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "月"),
                    (2, "火"),
                    (3, "水"),
                    (4, "木"),
                    (5, "金"),
                    (6, "土"),
                    (7, "日"),
                ],
                null=True,
                verbose_name="曜日",
            ),
        ),
        migrations.AddField(
            model_name="studentschool",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="終了時間"),
        ),
        migrations.AddField(
            model_name="studentschool",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
    ]
