# Generated by Django 4.2.26 on 2025-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_create_fs_discount_tables_postgres"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
    ]
