# Generated by Django 4.2.26 on 2025-12-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_merge_20251213_1427"),
        ("students", "0019_merge"),
    ]

    operations = []
