# Generated by Django 4.2.26 on 2025-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_first_fiscal_year_free"),
        ("students", "0020_merge_0012_merge_20251213_1427_0019_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="bankaccountchangerequest",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="friendshipregistration",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="friendshipregistration",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="fsdiscount",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="fsdiscount",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="studentguardian",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="studentguardian",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="studentschool",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="studentschool",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="suspensionrequest",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="suspensionrequest",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="trialbooking",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="trialbooking",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="会社ID"),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="会社",
            ),
        ),
    ]
