# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_add_first_fiscal_year_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
