# Generated by Django 4.2.27 on 2025-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_guardian_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='debit_start_date',
            field=models.CharField(blank=True, help_text='YYYY/MM形式', max_length=10, verbose_name='引落開始月'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('jaccs', 'JACCS'), ('ufjfactors', 'UFJファクター'), ('chukyo_finance', '中京ファイナンス'), ('', '未設定')], default='', help_text='口座振替の決済代行会社（JACCS/UFJファクター等）', max_length=20, verbose_name='決済代行会社'),
        ),
    ]
