# Generated by Django 4.2.27 on 2026-01-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_add_payment_provider_to_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensionrequest',
            name='return_day',
            field=models.DateField(blank=True, help_text='復会月内の具体的な日付（任意）', null=True, verbose_name='復会予定日'),
        ),
    ]
