# Generated by Django 4.2.27 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_suspensionrequest_return_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='referral_code',
            field=models.CharField(
                blank=True,
                help_text='友達紹介用の10桁コード（英数字+記号）',
                max_length=10,
                null=True,
                unique=True,
                verbose_name='紹介コード'
            ),
        ),
    ]
