# Generated by Django 4.2.27 on 2026-01-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_add_first_fiscal_year_free'),
        ('students', '0026_add_student_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbooking',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_bookings', to='schools.classschedule', verbose_name='クラススケジュール'),
        ),
    ]
