# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ALL", "全員"),
                            ("STUDENTS", "生徒"),
                            ("GUARDIANS", "保護者"),
                            ("STAFF", "スタッフ"),
                            ("SCHOOL", "校舎指定"),
                            ("GRADE", "学年指定"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="配信対象",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("SCHEDULED", "予約"),
                            ("SENT", "送信済み"),
                            ("CANCELLED", "キャンセル"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信予定日時"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信日時"
                    ),
                ),
                ("sent_count", models.IntegerField(default=0, verbose_name="送信数")),
                ("read_count", models.IntegerField(default=0, verbose_name="既読数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "お知らせ",
                "verbose_name_plural": "お知らせ",
                "db_table": "communication_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="既読日時"),
                ),
            ],
            options={
                "verbose_name": "お知らせ既読",
                "verbose_name_plural": "お知らせ既読",
                "db_table": "communication_announcement_reads",
            },
        ),
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                ("name", models.CharField(max_length=50, verbose_name="ボット名")),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("FAQ", "FAQ応答"),
                            ("SCHEDULE", "スケジュール確認"),
                            ("GENERAL", "一般応答"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="ボット種別",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="こんにちは！何かお手伝いできることはありますか？",
                        verbose_name="ウェルカムメッセージ",
                    ),
                ),
                (
                    "fallback_message",
                    models.TextField(
                        default="申し訳ございません。ご質問の内容を理解できませんでした。スタッフにお繋ぎしますか？",
                        verbose_name="フォールバックメッセージ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "ai_enabled",
                    models.BooleanField(default=False, verbose_name="AI応答有効"),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="AIモデル"
                    ),
                ),
                (
                    "ai_system_prompt",
                    models.TextField(
                        blank=True, null=True, verbose_name="AIシステムプロンプト"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ボット設定",
                "verbose_name_plural": "ボット設定",
                "db_table": "communication_bot_configs",
            },
        ),
        migrations.CreateModel(
            name="BotConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                ("user_input", models.TextField(verbose_name="ユーザー入力")),
                ("bot_response", models.TextField(verbose_name="ボット応答")),
                (
                    "is_ai_response",
                    models.BooleanField(default=False, verbose_name="AI応答"),
                ),
                (
                    "escalated_to_staff",
                    models.BooleanField(default=False, verbose_name="スタッフ転送"),
                ),
                (
                    "escalated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="転送日時"
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="役に立った"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "ボット会話",
                "verbose_name_plural": "ボット会話",
                "db_table": "communication_bot_conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotFAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="カテゴリ"
                    ),
                ),
                ("question", models.TextField(verbose_name="質問")),
                ("keywords", models.JSONField(default=list, verbose_name="キーワード")),
                ("answer", models.TextField(verbose_name="回答")),
                (
                    "next_action",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="次のアクション",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ボットFAQ",
                "verbose_name_plural": "ボットFAQ",
                "db_table": "communication_bot_faqs",
                "ordering": ["category", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "内部（スタッフ間）"),
                            ("EXTERNAL", "外部（保護者・生徒）"),
                            ("SUPPORT", "サポート"),
                            ("BOT", "ボット"),
                        ],
                        max_length=20,
                        verbose_name="チャンネル種別",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="チャンネル名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="アーカイブ済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "チャンネル",
                "verbose_name_plural": "チャンネル",
                "db_table": "communication_channels",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "管理者"),
                            ("MEMBER", "メンバー"),
                            ("READONLY", "閲覧のみ"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="役割",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終既読日時"
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="ミュート"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="参加日時"),
                ),
            ],
            options={
                "verbose_name": "チャンネルメンバー",
                "verbose_name_plural": "チャンネルメンバー",
                "db_table": "communication_channel_members",
            },
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("PHONE_IN", "電話（受信）"),
                            ("PHONE_OUT", "電話（発信）"),
                            ("EMAIL_IN", "メール（受信）"),
                            ("EMAIL_OUT", "メール（送信）"),
                            ("VISIT", "来校"),
                            ("MEETING", "面談"),
                            ("ONLINE_MEETING", "オンライン面談"),
                            ("CHAT", "チャット"),
                            ("OTHER", "その他"),
                        ],
                        max_length=20,
                        verbose_name="対応種別",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "低"),
                            ("MEDIUM", "中"),
                            ("HIGH", "高"),
                            ("URGENT", "緊急"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "対応中"),
                            ("PENDING", "保留"),
                            ("RESOLVED", "解決"),
                            ("CLOSED", "クローズ"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="フォローアップ日"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="フォローアップメモ"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決日時"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="タグ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "対応履歴",
                "verbose_name_plural": "対応履歴",
                "db_table": "communication_contact_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactLogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "対応履歴コメント",
                "verbose_name_plural": "対応履歴コメント",
                "db_table": "communication_contact_log_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "フィードブックマーク",
                "verbose_name_plural": "フィードブックマーク",
                "db_table": "communication_feed_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="FeedComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="コメント")),
                ("like_count", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "フィードコメント",
                "verbose_name_plural": "フィードコメント",
                "db_table": "communication_feed_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedCommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "コメントいいね",
                "verbose_name_plural": "コメントいいね",
                "db_table": "communication_feed_comment_likes",
            },
        ),
        migrations.CreateModel(
            name="FeedLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "フィードいいね",
                "verbose_name_plural": "フィードいいね",
                "db_table": "communication_feed_likes",
            },
        ),
        migrations.CreateModel(
            name="FeedMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "画像"), ("VIDEO", "動画")],
                        max_length=20,
                        verbose_name="メディア種別",
                    ),
                ),
                ("file_url", models.URLField(verbose_name="ファイルURL")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="サムネイルURL"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ファイル名"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ファイルサイズ"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="幅"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="高さ"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="長さ（秒）"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "フィードメディア",
                "verbose_name_plural": "フィードメディア",
                "db_table": "communication_feed_media",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "テキスト"),
                            ("IMAGE", "画像"),
                            ("VIDEO", "動画"),
                            ("GALLERY", "ギャラリー（複数画像）"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="投稿種別",
                    ),
                ),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "全体公開"),
                            ("SCHOOL", "校舎限定"),
                            ("GRADE", "学年限定"),
                            ("STAFF", "スタッフのみ"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="公開範囲",
                    ),
                ),
                (
                    "hashtags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ハッシュタグ"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="固定表示"),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="固定日時"
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="コメント許可"),
                ),
                (
                    "allow_likes",
                    models.BooleanField(default=True, verbose_name="いいね許可"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="コメント数"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="閲覧数")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開済み"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="公開日時"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除済み"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "フィード投稿",
                "verbose_name_plural": "フィード投稿",
                "db_table": "communication_feed_posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "テキスト"),
                            ("IMAGE", "画像"),
                            ("FILE", "ファイル"),
                            ("SYSTEM", "システム"),
                            ("BOT", "ボット"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="メッセージ種別",
                    ),
                ),
                (
                    "is_bot_message",
                    models.BooleanField(default=False, verbose_name="ボットメッセージ"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="添付ファイルURL"
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="添付ファイル名",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="編集済み"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="編集日時"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "メッセージ",
                "verbose_name_plural": "メッセージ",
                "db_table": "communication_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="既読日時"),
                ),
            ],
            options={
                "verbose_name": "メッセージ既読",
                "verbose_name_plural": "メッセージ既読",
                "db_table": "communication_message_reads",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "新着メッセージ"),
                            ("MENTION", "メンション"),
                            ("LESSON_REMINDER", "授業リマインダー"),
                            ("LESSON_CANCEL", "授業キャンセル"),
                            ("MAKEUP_REQUEST", "振替リクエスト"),
                            ("MAKEUP_APPROVED", "振替承認"),
                            ("PAYMENT_DUE", "支払い期限"),
                            ("SYSTEM", "システム通知"),
                        ],
                        max_length=30,
                        verbose_name="通知種別",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "link_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="リンク種別"
                    ),
                ),
                (
                    "link_id",
                    models.UUIDField(blank=True, null=True, verbose_name="リンクID"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="既読日時"
                    ),
                ),
                (
                    "is_push_sent",
                    models.BooleanField(default=False, verbose_name="プッシュ送信済み"),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="プッシュ送信日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "communication_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
