# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="students.guardian",
                verbose_name="保護者",
            ),
        ),
    ]
