# Generated by Django 4.2.27 on 2025-12-08 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_task_id_ref"),
        ("schools", "0010_add_lesson_calendar_csv_fields"),
        ("communications", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(verbose_name="テナントID")),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="校舎名（スナップショット）",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="保護者名（スナップショット）",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="その他",
                        max_length=100,
                        verbose_name="ブランド名（スナップショット）",
                    ),
                ),
                ("content", models.TextField(verbose_name="メッセージ内容")),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("GUARDIAN", "保護者"),
                            ("STAFF", "スタッフ"),
                            ("BOT", "ボット"),
                        ],
                        max_length=20,
                        verbose_name="送信者タイプ",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="タイムスタンプ"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_logs",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_logs",
                        to="students.guardian",
                        verbose_name="保護者",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_logs",
                        to="communications.message",
                        verbose_name="メッセージ",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_logs",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットログ",
                "verbose_name_plural": "チャットログ",
                "db_table": "communication_chat_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-timestamp"],
                        name="communicati_tenant__a8a1a6_idx",
                    ),
                    models.Index(
                        fields=["school", "-timestamp"],
                        name="communicati_school__057c21_idx",
                    ),
                    models.Index(
                        fields=["guardian", "-timestamp"],
                        name="communicati_guardia_3c700a_idx",
                    ),
                    models.Index(
                        fields=["brand", "-timestamp"],
                        name="communicati_brand_i_6073d6_idx",
                    ),
                ],
            },
        ),
    ]
