# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_add_chat_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='botconversation',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='botfaq',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant_id',
            field=models.UUIDField(verbose_name='会社ID'),
        ),
    ]
