# Generated by Django 4.2.27 on 2025-12-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_add_first_fiscal_year_free'),
        ('communications', '0005_alter_announcement_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='target_brands',
            field=models.ManyToManyField(blank=True, related_name='visible_feed_posts', to='schools.brand', verbose_name='対象ブランド'),
        ),
    ]
