# Generated by Django 4.2.27 on 2025-12-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_add_feed_target_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='publish_end_at',
            field=models.DateTimeField(blank=True, help_text='指定しない場合は無期限', null=True, verbose_name='公開終了日時'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='publish_start_at',
            field=models.DateTimeField(blank=True, help_text='指定しない場合は即時公開', null=True, verbose_name='公開開始日時'),
        ),
    ]
