# Generated by Django 4.2.27 on 2026-01-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_add_message_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmember',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='ピン留め'),
        ),
    ]
