# Generated by Django 4.2.27 on 2026-01-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_add_is_pinned_to_channel_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='題名'),
        ),
    ]
