# Generated by Django 4.2.27 on 2026-01-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_add_class_schedule_to_trial_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0011_add_title_to_feedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('call_direction', models.CharField(choices=[('incoming', '着信'), ('outgoing', '発信')], default='incoming', max_length=20, verbose_name='発信/着信')),
                ('call_result', models.CharField(choices=[('connected', '通話'), ('no_answer', '不在'), ('busy', '話し中'), ('voicemail', '留守電')], default='connected', max_length=20, verbose_name='通話結果')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tel_memos', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tel_memos', to='students.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': 'TEL登録メモ',
                'verbose_name_plural': 'TEL登録メモ',
                'db_table': 'communications_tel_memo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '通常'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=20, verbose_name='優先度')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('completed', '完了')], default='pending', max_length=20, verbose_name='状態')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_message_memos', to=settings.AUTH_USER_MODEL, verbose_name='完了者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_memos', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_memos', to='students.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': '伝言メモ',
                'verbose_name_plural': '伝言メモ',
                'db_table': 'communications_message_memo',
                'ordering': ['-created_at'],
            },
        ),
    ]
