# Generated by Django 4.2.26 on 2026-01-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0012_add_memo_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpost",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "申請中"),
                    ("approved", "承認済"),
                    ("rejected", "却下"),
                ],
                default="approved",
                max_length=20,
                verbose_name="承認ステータス",
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_feed_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="承認者",
            ),
        ),
    ]
