#!/usr/bin/env bash
set -euo pipefail

# デバッグ実行ログを docs/debug/ に保存するスクリプト
# 使い方: ./tools/logrun.sh [command] または make logcheck

cd "$(dirname "$0")/.."

TS="$(date +"%Y-%m-%d %H:%M:%S")"
STAMP="$(date +"%Y%m%d_%H%M%S")"
OUT="docs/debug/run_${STAMP}.md"

mkdir -p docs/debug logs

# 実行するコマンド（引数があればそれを使用、なければデフォルト）
CMD="${*:-make check}"

{
  echo "# Debug Run ${STAMP}"
  echo ""
  echo "- Time: ${TS}"
  echo "- Branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'N/A')"
  echo "- Commit: $(git rev-parse --short HEAD 2>/dev/null || echo 'N/A')"
  echo "- Working Dir: $(pwd)"
  echo ""
  echo "## Commands"
  echo "\`\`\`bash"
  echo "${CMD}"
  echo "\`\`\`"
  echo ""
  echo "## Output"
  echo "\`\`\`"
} > "$OUT"

# コマンドを実行し、標準出力/エラーを docs に追記
EXIT_CODE=0
eval "${CMD}" >> "$OUT" 2>&1 || EXIT_CODE=$?

{
  echo "\`\`\`"
  echo ""
  echo "## Result"
  if [ $EXIT_CODE -eq 0 ]; then
    echo "- ✅ Success (exit code: 0)"
  else
    echo "- ❌ Failed (exit code: ${EXIT_CODE})"
  fi
  echo ""
  echo "---"
  echo "_Generated by tools/logrun.sh_"
} >> "$OUT"

echo ""
echo "========================================"
echo "Log saved: $OUT"
echo "Exit code: $EXIT_CODE"
echo "========================================"

exit $EXIT_CODE
