# Generated by Django 4.2.26 on 2025-12-02 14:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certification_code",
                    models.CharField(max_length=50, verbose_name="検定コード"),
                ),
                (
                    "certification_name",
                    models.CharField(max_length=200, verbose_name="検定名"),
                ),
                (
                    "certification_type",
                    models.CharField(
                        choices=[
                            ("eiken", "英検"),
                            ("kanken", "漢検"),
                            ("suken", "数検"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="検定種別",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="級・レベル"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "exam_date",
                    models.DateField(blank=True, null=True, verbose_name="試験日"),
                ),
                (
                    "exam_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="検定料",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T12_検定",
                "verbose_name_plural": "T12_検定",
                "db_table": "t12_certifications",
                "ordering": ["year", "certification_type"],
            },
        ),
        migrations.CreateModel(
            name="CertificationEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "申込済"),
                            ("confirmed", "確定"),
                            ("cancelled", "キャンセル"),
                            ("passed", "合格"),
                            ("failed", "不合格"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申込日時"),
                ),
                (
                    "exam_fee",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="検定料"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="割引額",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="確定金額"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="スコア"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "T56_検定申込",
                "verbose_name_plural": "T56_検定申込",
                "db_table": "t56_certification_enrollments",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_no",
                    models.CharField(max_length=30, verbose_name="契約番号"),
                ),
                ("contract_date", models.DateField(verbose_name="契約日")),
                ("start_date", models.DateField(verbose_name="開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有効"),
                            ("paused", "休止中"),
                            ("cancelled", "解約"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "monthly_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="月額合計",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "契約",
                "verbose_name_plural": "契約",
                "db_table": "t03_contracts",
                "ordering": ["-contract_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(max_length=50, verbose_name="コースコード"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=100, verbose_name="コース名"),
                ),
                (
                    "course_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="設定した場合、商品積み上げではなくこの料金を使用",
                        max_digits=10,
                        null=True,
                        verbose_name="コース料金",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T08_コース",
                "verbose_name_plural": "T08_コース",
                "db_table": "t08_courses",
                "ordering": ["sort_order", "course_code"],
            },
        ),
        migrations.CreateModel(
            name="CourseItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="単価上書き",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T52_コース商品構成",
                "verbose_name_plural": "T52_コース商品構成",
                "db_table": "t52_course_items",
                "ordering": ["course", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CourseRequiredSeminar",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auto_enroll",
                    models.BooleanField(default=True, verbose_name="自動申込"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T54_コース必須講習",
                "verbose_name_plural": "T54_コース必須講習",
                "db_table": "t54_course_required_seminars",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(max_length=20, verbose_name="割引コード"),
                ),
                (
                    "discount_name",
                    models.CharField(max_length=100, verbose_name="割引名"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("sibling", "兄弟割引"),
                            ("multi_subject", "複数科目割引"),
                            ("campaign", "キャンペーン"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="割引種別",
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[("percentage", "割合"), ("fixed", "固定金額")],
                        default="percentage",
                        max_length=20,
                        verbose_name="計算種別",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="値"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="適用開始日"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="適用終了日"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T07_割引",
                "verbose_name_plural": "T07_割引",
                "db_table": "t07_discounts",
                "ordering": ["discount_code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="商品コード"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="商品名"),
                ),
                (
                    "product_name_short",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="商品名略称"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("tuition", "授業料"),
                            ("monthly_fee", "月会費"),
                            ("facility", "設備費"),
                            ("textbook", "教材費"),
                            ("expense", "諸経費"),
                            ("enrollment", "入会金"),
                            ("other", "その他"),
                        ],
                        default="tuition",
                        max_length=20,
                        verbose_name="商品種別",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="基本価格",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        max_digits=5,
                        verbose_name="税率",
                    ),
                ),
                (
                    "is_tax_included",
                    models.BooleanField(default=True, verbose_name="税込"),
                ),
                (
                    "prorate_first_month",
                    models.BooleanField(
                        default=False,
                        help_text="入会月の授業料を日割り計算する",
                        verbose_name="初月日割り",
                    ),
                ),
                (
                    "is_one_time",
                    models.BooleanField(default=False, verbose_name="一回きり"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T03_商品",
                "verbose_name_plural": "T03_商品",
                "db_table": "t03_products",
                "ordering": ["sort_order", "product_code"],
            },
        ),
        migrations.CreateModel(
            name="Seminar",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seminar_code",
                    models.CharField(max_length=50, verbose_name="講習コード"),
                ),
                (
                    "seminar_name",
                    models.CharField(max_length=200, verbose_name="講習名"),
                ),
                (
                    "seminar_type",
                    models.CharField(
                        choices=[
                            ("spring", "春期講習"),
                            ("summer", "夏期講習"),
                            ("autumn", "秋期講習"),
                            ("winter", "冬期講習"),
                            ("special", "特別講習"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="講習種別",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="価格"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "T11_講習",
                "verbose_name_plural": "T11_講習",
                "db_table": "t11_seminars",
                "ordering": ["year", "seminar_type", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SeminarEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "申込済"),
                            ("confirmed", "確定"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申込日時"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="単価"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="割引額",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="確定金額"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="必須講習"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "T55_講習申込",
                "verbose_name_plural": "T55_講習申込",
                "db_table": "t55_seminar_enrollments",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_month",
                    models.CharField(
                        help_text="例: 2025-04", max_length=7, verbose_name="請求月"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="単価"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="割引額",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="確定金額"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_items",
                        to="contracts.contract",
                        verbose_name="契約",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_items",
                        to="contracts.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "T04_生徒商品",
                "verbose_name_plural": "T04_生徒商品",
                "db_table": "t04_student_items",
                "ordering": ["-billing_month", "student"],
            },
        ),
    ]
