# Generated by Django 4.2.26 on 2025-12-02 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pack_code",
                    models.CharField(max_length=50, verbose_name="パックコード"),
                ),
                (
                    "pack_name",
                    models.CharField(max_length=100, verbose_name="パック名"),
                ),
                (
                    "pack_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="設定した場合、コース積み上げではなくこの料金を使用",
                        max_digits=10,
                        null=True,
                        verbose_name="パック料金",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("none", "割引なし"),
                            ("percentage", "割合割引"),
                            ("fixed", "固定割引"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="割引種別",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="割合の場合は%、固定の場合は円",
                        max_digits=10,
                        verbose_name="割引値",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packs",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
            ],
            options={
                "verbose_name": "T09_パック",
                "verbose_name_plural": "T09_パック",
                "db_table": "t09_packs",
                "ordering": ["sort_order", "pack_code"],
                "unique_together": {("tenant_id", "pack_code")},
            },
        ),
        migrations.CreateModel(
            name="PackCourse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_packs",
                        to="contracts.course",
                        verbose_name="コース",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_courses",
                        to="contracts.pack",
                        verbose_name="パック",
                    ),
                ),
            ],
            options={
                "verbose_name": "T53_パックコース構成",
                "verbose_name_plural": "T53_パックコース構成",
                "db_table": "t53_pack_courses",
                "ordering": ["pack", "sort_order"],
                "unique_together": {("pack", "course")},
            },
        ),
    ]
