# Generated by Django 4.2.26 on 2025-12-03 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_productprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="設定した場合、商品の基本価格ではなくこの価格を使用",
                        max_digits=10,
                        null=True,
                        verbose_name="価格上書き",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_items",
                        to="contracts.pack",
                        verbose_name="パック",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_packs",
                        to="contracts.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "T52_パック商品構成",
                "verbose_name_plural": "T52_パック商品構成",
                "db_table": "t52_pack_items",
                "ordering": ["pack", "sort_order"],
                "unique_together": {("pack", "product")},
            },
        ),
    ]
