# Generated by Django 4.2.26 on 2025-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_packitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["sort_order", "product_code"],
                "verbose_name": "T03_契約全部",
                "verbose_name_plural": "T03_契約全部",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="discount_max",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="割引Max"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mile",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="マイル"
            ),
        ),
    ]
