# Generated by Django 4.2.26 on 2025-12-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_add_brand_school"),
        ("contracts", "0006_alter_product_options_product_discount_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packs",
                to="schools.grade",
                verbose_name="対象学年",
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packs",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="設定した場合、商品積み上げではなくこの料金を使用",
                max_digits=10,
                null=True,
                verbose_name="授業料",
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="pack_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="設定した場合、コース積み上げではなくこの料金を使用",
                max_digits=10,
                null=True,
                verbose_name="授業料",
            ),
        ),
    ]
