# Generated by Django 4.2.26 on 2025-12-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_pack_grade_pack_school_alter_course_course_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="prorate_first_month",
        ),
    ]
