# Generated by Django 4.2.26 on 2025-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_remove_prorate_first_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_first_year_free",
            field=models.BooleanField(
                default=False,
                help_text="チェックすると契約から12ヶ月間は無料、13ヶ月目から料金発生",
                verbose_name="1年目無料",
            ),
        ),
    ]
