# Generated by Django 4.2.26 on 2025-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_add_first_year_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_tax_included",
        ),
        migrations.AddField(
            model_name="product",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("included", "税込"),
                    ("excluded", "税抜"),
                    ("exempt", "非課税"),
                ],
                default="included",
                max_length=20,
                verbose_name="税区分",
            ),
        ),
    ]
