# Generated by Django 4.2.26 on 2025-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_change_tax_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tax_type",
            field=models.CharField(
                choices=[("1", "1:税込"), ("2", "2:税抜"), ("3", "3:非課税")],
                default="1",
                max_length=20,
                verbose_name="税区分",
            ),
        ),
    ]
