# Generated by Django 4.2.26 on 2025-12-04 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("contracts", "0011_update_tax_type_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSet",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "set_code",
                    models.CharField(max_length=50, verbose_name="セットコード"),
                ),
                ("set_name", models.CharField(max_length=100, verbose_name="セット名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_sets",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
            ],
            options={
                "verbose_name": "T06_商品セット",
                "verbose_name_plural": "T06_商品セット",
                "db_table": "t06_product_sets",
                "ordering": ["sort_order", "set_code"],
                "unique_together": {("tenant_id", "set_code")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="product_set",
            field=models.ForeignKey(
                blank=True,
                help_text="入会金＋教材費＋授業料などの商品組み合わせ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="contracts.productset",
                verbose_name="商品セット",
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="product_set",
            field=models.ForeignKey(
                blank=True,
                help_text="入会金＋教材費＋授業料などの商品組み合わせ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packs",
                to="contracts.productset",
                verbose_name="商品セット",
            ),
        ),
        migrations.CreateModel(
            name="ProductSetItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="設定した場合、商品の基本価格ではなくこの価格を使用",
                        max_digits=10,
                        null=True,
                        verbose_name="価格上書き",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_sets",
                        to="contracts.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "product_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contracts.productset",
                        verbose_name="商品セット",
                    ),
                ),
            ],
            options={
                "verbose_name": "T06b_商品セット明細",
                "verbose_name_plural": "T06b_商品セット明細",
                "db_table": "t06b_product_set_items",
                "ordering": ["product_set", "sort_order"],
                "unique_together": {("product_set", "product")},
            },
        ),
    ]
