# Generated by Django 4.2.27 on 2025-12-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_add_lesson_calendar_csv_fields"),
        ("contracts", "0013_add_tenant_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                help_text="0=日, 1=月, 2=火, 3=水, 4=木, 5=金, 6=土",
                null=True,
                verbose_name="曜日",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="終了時間"),
        ),
        migrations.AddField(
            model_name="contract",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
        migrations.AddField(
            model_name="course",
            name="promotion_course",
            field=models.ForeignKey(
                blank=True,
                help_text="学年が上がった際に自動で昇格するコース（例：RYellow→Red）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotion_from",
                to="contracts.course",
                verbose_name="昇格先コース",
            ),
        ),
    ]
