# Generated by Django 4.2.27 on 2025-12-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_add_brand_school"),
        ("contracts", "0014_add_schedule_and_promotion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_items",
                to="schools.brand",
                verbose_name="ブランド",
            ),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_items",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
    ]
