# Generated by Django 4.2.26 on 2025-12-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_add_brand_student_to_studentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_items",
                to="contracts.course",
                verbose_name="コース",
            ),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="開始日"),
        ),
    ]
