# Generated by Django 4.2.26 on 2025-12-10 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0011_alter_lessoncalendar_unique"),
        ("tenants", "0001_initial"),
        ("contracts", "0016_studentitem_course_studentitem_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_enrollment_tuition",
            field=models.BooleanField(
                default=False,
                help_text="チェックすると入会日に基づいて追加チケット数を自動計算（フロント側）",
                verbose_name="入会時授業料",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="per_ticket_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="入会時授業料の場合、1チケットあたりの単価",
                max_digits=10,
                null=True,
                verbose_name="1チケット単価",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("tuition", "授業料"),
                    ("monthly_fee", "月会費"),
                    ("facility", "設備費"),
                    ("textbook", "教材費"),
                    ("expense", "諸経費"),
                    ("enrollment", "入会金"),
                    ("enrollment_tuition", "入会時授業料"),
                    ("enrollment_monthly_fee", "入会時月会費"),
                    ("enrollment_facility", "入会時設備費"),
                    ("enrollment_textbook", "入会時教材費"),
                    ("enrollment_expense", "入会時諸経費"),
                    ("enrollment_management", "入会時総合指導管理費"),
                    ("seminar", "講習会"),
                    ("seminar_spring", "春期講習会"),
                    ("seminar_summer", "夏期講習会"),
                    ("seminar_winter", "冬期講習会"),
                    ("required_seminar", "必須講習会"),
                    ("required_course", "必須講座"),
                    ("test_prep", "テスト対策費"),
                    ("required_test_prep", "必須テスト対策費"),
                    ("mock_exam", "模試代"),
                    ("required_mock_exam", "必須模試代"),
                    ("exam_prep", "入試対策費"),
                    ("required_exam_prep", "必須入試対策費"),
                    ("certification_fee_1", "検定料1"),
                    ("certification_fee_2", "検定料2"),
                    ("certification_fee_3", "検定料3"),
                    ("certification_fee_4", "検定料4"),
                    ("extra_tuition", "追加授業料"),
                    ("instructor_fee", "講師指名料"),
                    ("bag", "バッグ"),
                    ("abacus", "そろばん本体代"),
                    ("snack", "おやつ"),
                    ("lunch", "お弁当"),
                    ("childcare_ticket", "保育回数券"),
                    ("custody", "預り料"),
                    ("transportation", "送迎費"),
                    ("management", "総合指導管理費"),
                    ("rent", "家賃"),
                    ("other", "その他"),
                ],
                default="tuition",
                max_length=30,
                verbose_name="商品種別",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        help_text="T10000001形式（Tプレフィックス）",
                        max_length=20,
                        verbose_name="チケットコード",
                    ),
                ),
                (
                    "ticket_name",
                    models.CharField(max_length=200, verbose_name="チケット名"),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("1", "1：授業"),
                            ("5", "5：講習会"),
                            ("6", "6：模試"),
                            ("7", "7:テスト対策"),
                            ("8", "8：自宅受講"),
                            ("0", "その他"),
                        ],
                        default="1",
                        max_length=10,
                        verbose_name="チケット種類",
                    ),
                ),
                (
                    "ticket_category",
                    models.CharField(
                        choices=[
                            ("1", "通常"),
                            ("2", "振替"),
                            ("3", "年マタギ"),
                            ("0", "その他"),
                        ],
                        default="1",
                        max_length=10,
                        verbose_name="チケット区別",
                    ),
                ),
                (
                    "transfer_day",
                    models.IntegerField(
                        blank=True,
                        help_text="0=日, 1=月, 2=火, 3=水, 4=木, 5=金, 6=土",
                        null=True,
                        verbose_name="振替曜日",
                    ),
                ),
                (
                    "transfer_group",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="振替Group"
                    ),
                ),
                (
                    "consumption_symbol",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="消化記号"
                    ),
                ),
                (
                    "annual_weekly",
                    models.IntegerField(
                        default=42, help_text="年間授業回数", verbose_name="年間/週"
                    ),
                ),
                (
                    "max_per_lesson",
                    models.IntegerField(
                        default=1,
                        help_text="1回あたりの消費チケット数",
                        verbose_name="Max値",
                    ),
                ),
                (
                    "total_tickets",
                    models.IntegerField(
                        default=42,
                        help_text="年間合計チケット数",
                        verbose_name="チケット枚数",
                    ),
                ),
                (
                    "calendar_flag",
                    models.IntegerField(default=2, verbose_name="カレンダーフラグ"),
                ),
                (
                    "year_carryover",
                    models.BooleanField(
                        default=False,
                        help_text="年度をまたいで利用可能か",
                        verbose_name="年マタギ利用",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有効期限"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "T07_チケット",
                "verbose_name_plural": "T07_チケット",
                "db_table": "t07_tickets",
                "ordering": ["ticket_code"],
                "unique_together": {("tenant_id", "ticket_code")},
            },
        ),
        migrations.CreateModel(
            name="PackTicket",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="付与枚数")),
                ("per_week", models.IntegerField(default=1, verbose_name="週あたり")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_tickets",
                        to="contracts.pack",
                        verbose_name="パック",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_packs",
                        to="contracts.ticket",
                        verbose_name="チケット",
                    ),
                ),
            ],
            options={
                "verbose_name": "T09b_パックチケット",
                "verbose_name_plural": "T09b_パックチケット",
                "db_table": "t09b_pack_tickets",
                "ordering": ["pack", "sort_order"],
                "unique_together": {("pack", "ticket")},
            },
        ),
        migrations.CreateModel(
            name="CourseTicket",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="年間付与されるチケット枚数",
                        verbose_name="付与枚数",
                    ),
                ),
                (
                    "per_week",
                    models.IntegerField(
                        default=1,
                        help_text="週あたりの授業回数",
                        verbose_name="週あたり",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_tickets",
                        to="contracts.course",
                        verbose_name="コース",
                    ),
                ),
                (
                    "tenant_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_courses",
                        to="contracts.ticket",
                        verbose_name="チケット",
                    ),
                ),
            ],
            options={
                "verbose_name": "T08b_コースチケット",
                "verbose_name_plural": "T08b_コースチケット",
                "db_table": "t08b_course_tickets",
                "ordering": ["course", "sort_order"],
                "unique_together": {("course", "ticket")},
            },
        ),
    ]
