# Generated by Django 4.2.26 on 2025-12-14 06:17
# Modified: Use SeparateDatabaseAndState for StudentDiscount since table already exists

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_add_discount_operation_log"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0012_merge_20251213_1427"),
        ("contracts", "0023_add_contract_history_audit_log"),
    ]

    operations = [
        # StudentDiscount - table already exists, only update Django state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="StudentDiscount",
                    fields=[
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                        ),
                        (
                            "tenant_id",
                            models.UUIDField(db_index=True, verbose_name="テナントID"),
                        ),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="削除日時"
                            ),
                        ),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "old_id",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=50,
                                verbose_name="旧システムID",
                            ),
                        ),
                        (
                            "discount_name",
                            models.CharField(max_length=200, verbose_name="割引名"),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=0,
                                help_text="マイナス値で割引",
                                max_digits=10,
                                verbose_name="金額",
                            ),
                        ),
                        (
                            "discount_unit",
                            models.CharField(
                                choices=[("yen", "円"), ("percent", "%")],
                                default="yen",
                                max_length=10,
                                verbose_name="割引単位",
                            ),
                        ),
                        (
                            "start_date",
                            models.DateField(blank=True, null=True, verbose_name="開始日"),
                        ),
                        (
                            "end_date",
                            models.DateField(blank=True, null=True, verbose_name="終了日"),
                        ),
                        (
                            "is_recurring",
                            models.BooleanField(default=False, verbose_name="繰り返し"),
                        ),
                        (
                            "is_auto",
                            models.BooleanField(default=False, verbose_name="自動割引"),
                        ),
                        (
                            "end_condition",
                            models.CharField(
                                choices=[
                                    ("once", "１回だけ"),
                                    ("monthly", "毎月"),
                                    ("until_end_date", "終了日まで"),
                                ],
                                default="once",
                                max_length=20,
                                verbose_name="終了条件",
                            ),
                        ),
                        ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                        ("notes", models.TextField(blank=True, verbose_name="備考")),
                        (
                            "brand",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="student_discounts",
                                to="schools.brand",
                                verbose_name="ブランド",
                            ),
                        ),
                        (
                            "contract",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="student_discounts",
                                to="contracts.contract",
                                verbose_name="契約",
                            ),
                        ),
                        (
                            "guardian",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="student_discounts",
                                to="students.guardian",
                                verbose_name="保護者",
                            ),
                        ),
                        (
                            "student",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="student_discounts",
                                to="students.student",
                                verbose_name="生徒",
                            ),
                        ),
                        (
                            "student_item",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="student_discounts",
                                to="contracts.studentitem",
                                verbose_name="請求項目",
                            ),
                        ),
                        (
                            "tenant_ref",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="%(app_label)s_%(class)s_set",
                                to="tenants.tenant",
                                verbose_name="テナント",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "T06_生徒割引",
                        "verbose_name_plural": "T06_生徒割引",
                        "db_table": "t06_student_discounts",
                        "ordering": ["-start_date", "student"],
                    },
                ),
            ],
            database_operations=[
                # No database operations - table already exists
            ],
        ),

        # DiscountOperationLog model - actually create this one
        migrations.CreateModel(
            name="DiscountOperationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("add", "追加"),
                            ("update", "変更"),
                            ("delete", "削除"),
                        ],
                        max_length=10,
                        verbose_name="操作種別",
                    ),
                ),
                (
                    "discount_name",
                    models.CharField(max_length=200, verbose_name="割引名"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="適用された割引額",
                        max_digits=10,
                        verbose_name="割引額",
                    ),
                ),
                (
                    "discount_unit",
                    models.CharField(
                        default="yen", max_length=10, verbose_name="割引単位"
                    ),
                ),
                (
                    "discount_max",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="適用時点の商品の割引Max",
                        max_digits=10,
                        verbose_name="割引Max",
                    ),
                ),
                (
                    "total_discount_before",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="操作前の合計割引額",
                    ),
                ),
                (
                    "total_discount_after",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="操作後の合計割引額",
                    ),
                ),
                (
                    "excess_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="割引Maxを超過した金額（校舎負担）",
                        max_digits=10,
                        verbose_name="校舎負担分",
                    ),
                ),
                (
                    "operated_by_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="操作者名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IPアドレス"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "割引操作履歴",
                "verbose_name_plural": "割引操作履歴",
                "db_table": "discount_operation_logs",
                "ordering": ["-created_at"],
            },
        ),

        # Add ForeignKey fields to DiscountOperationLog
        migrations.AddField(
            model_name="discountoperationlog",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_excess_logs",
                to="schools.brand",
                verbose_name="ブランド",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_logs",
                to="contracts.contract",
                verbose_name="契約",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="operated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_operations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作者",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_excess_logs",
                to="schools.school",
                verbose_name="担当校舎",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_logs",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="student_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="contracts.studentdiscount",
                verbose_name="割引",
            ),
        ),
        migrations.AddField(
            model_name="discountoperationlog",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),

        # Indexes for DiscountOperationLog
        migrations.AddIndex(
            model_name="discountoperationlog",
            index=models.Index(
                fields=["contract", "-created_at"],
                name="discount_op_contrac_bd53da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountoperationlog",
            index=models.Index(
                fields=["student", "-created_at"], name="discount_op_student_ac0fc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountoperationlog",
            index=models.Index(
                fields=["school", "-created_at"], name="discount_op_school__e3a3c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountoperationlog",
            index=models.Index(
                fields=["operated_by", "-created_at"],
                name="discount_op_operate_e71dad_idx",
            ),
        ),
    ]
