# Generated by Django 4.2.26 on 2025-12-15 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("students", "0018_add_additional_ticket_models"),
        ("schools", "0021_add_additional_ticket_models"),
        ("lessons", "0007_add_additional_ticket_models"),
        ("contracts", "0024_add_discount_operation_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalTicket",
            fields=[
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="購入日"),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="購入枚数")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="単価"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="合計金額",
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="使用済み数"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="有効期限"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "購入待ち"),
                            ("purchased", "購入済み"),
                            ("partially_used", "一部使用"),
                            ("fully_used", "使用完了"),
                            ("expired", "期限切れ"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "T10a_追加チケット",
                "verbose_name_plural": "T10a_追加チケット",
                "db_table": "t10a_additional_tickets",
                "ordering": ["-purchase_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalTicketDate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_date", models.DateField(verbose_name="対象日")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="使用済み"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "T10b_追加チケット対象日",
                "verbose_name_plural": "T10b_追加チケット対象日",
                "db_table": "t10b_additional_ticket_dates",
                "ordering": ["target_date"],
            },
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="discount",
        ),
        migrations.AddField(
            model_name="contract",
            name="old_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="旧システムID"
            ),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="old_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="旧システムID"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("sibling", "兄弟割引"),
                    ("multi_subject", "複数科目割引"),
                    ("campaign", "キャンペーン"),
                    ("mile", "マイル割引"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=20,
                verbose_name="割引種別",
            ),
        ),
        migrations.AlterField(
            model_name="studentitem",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                help_text="1=月, 2=火, 3=水, 4=木, 5=金, 6=土, 7=日",
                null=True,
                verbose_name="曜日",
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="system_audi_user_id_ac12ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditlog",
            index=models.Index(
                fields=["student"], name="system_audi_student_d01920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditlog",
            index=models.Index(
                fields=["guardian"], name="system_audi_guardia_116c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditlog",
            index=models.Index(
                fields=["contract"], name="system_audi_contrac_3fa845_idx"
            ),
        ),
        migrations.AddField(
            model_name="additionalticketdate",
            name="additional_ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_dates",
                to="contracts.additionalticket",
                verbose_name="追加チケット",
            ),
        ),
        migrations.AddField(
            model_name="additionalticketdate",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="additional_ticket_dates",
                to="lessons.attendance",
                verbose_name="出席",
            ),
        ),
        migrations.AddField(
            model_name="additionalticketdate",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="class_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="additional_tickets",
                to="schools.classschedule",
                verbose_name="クラススケジュール",
            ),
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="additional_tickets",
                to="contracts.course",
                verbose_name="コース",
            ),
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_tickets",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="student_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="additional_tickets",
                to="contracts.studentitem",
                verbose_name="生徒商品",
            ),
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="additionalticketdate",
            unique_together={("additional_ticket", "target_date")},
        ),
    ]
