# Generated by Django 4.2.26 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0026_add_first_fiscal_year_free"),
    ]

    operations = [
        # Djangoの状態だけ更新（DBは既にt10a_additional_ticketsで存在）
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="additionalticket",
                    table="t10a_additional_tickets",
                ),
            ],
            database_operations=[],  # DBは既に正しいテーブル名なので何もしない
        ),
        migrations.AddField(
            model_name="additionalticket",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("ticket", "授業チケット"),
                    ("monthly_fee", "当月分月会費"),
                    ("facility", "当月分設備費"),
                    ("textbook", "当月分教材費"),
                    ("management", "当月分総合指導管理費"),
                    ("expense", "当月分諸経費"),
                    ("other", "その他"),
                ],
                default="ticket",
                max_length=20,
                verbose_name="種別",
            ),
        ),
    ]
