# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_first_fiscal_year_free'),
        ('contracts', '0027_add_item_type_to_additional_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalticket',
            options={'ordering': ['-purchase_date', 'student'], 'verbose_name': 'T10a_追加チケット', 'verbose_name_plural': 'T10a_追加チケット'},
        ),
        migrations.AlterField(
            model_name='additionalticket',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='additionalticket',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='additionalticketdate',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='additionalticketdate',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_apr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='4月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_aug',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='8月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_dec',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='12月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_feb',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='2月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_jan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_jul',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='7月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_jun',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='6月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_mar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='3月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_may',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='5月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_nov',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='11月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_oct',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='10月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='billing_price_sep',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='9月'),
        ),
        migrations.AlterField(
            model_name='product',
            name='per_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='入会時授業料の場合、1チケットあたりの単価', max_digits=10, null=True, verbose_name='単価'),
        ),
    ]
