# Generated by Django 4.2 - Add is_active column to StudentDiscount database table
# The field was defined in model state but not in the database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0028_alter_additionalticket_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # No state changes - field already defined in state by migration 0024
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE t06_student_discounts ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;",
                    reverse_sql="ALTER TABLE t06_student_discounts DROP COLUMN IF EXISTS is_active;",
                ),
            ],
        ),
    ]
