# Generated by Django 4.2.27 on 2025-12-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_add_is_active_to_studentdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sort_order', 'course_code'], 'verbose_name': 'T08_金魚の糞付き', 'verbose_name_plural': 'T08_金魚の糞付き'},
        ),
        migrations.AddField(
            model_name='contract',
            name='selected_textbooks',
            field=models.ManyToManyField(blank=True, help_text='この契約で選択した教材費（月払い or 半年払い等）', related_name='selected_in_contracts', to='contracts.product', verbose_name='選択教材'),
        ),
    ]
