# Generated by Django 4.2.27 on 2025-12-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_add_first_fiscal_year_free'),
        ('contracts', '0030_add_selected_textbooks_to_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['discount_code'], 'verbose_name': 'T07_割引マスタ', 'verbose_name_plural': 'T07_割引マスタ'},
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_brand',
            field=models.ForeignKey(blank=True, help_text='空の場合は全ブランドに適用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='schools.brand', verbose_name='適用ブランド'),
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_category',
            field=models.CharField(choices=[('tuition', '授業料'), ('material', '教材費'), ('enrollment', '入会金'), ('monthly_fee', '月会費'), ('all', '全て')], default='all', help_text='この割引が適用される請求カテゴリ', max_length=20, verbose_name='適用カテゴリ'),
        ),
        migrations.AddField(
            model_name='discount',
            name='end_condition',
            field=models.CharField(choices=[('once', '1回だけ'), ('monthly', '毎月'), ('until_end_date', '終了日まで'), ('on_contract_decrease', '契約数が減った時'), ('on_brand_withdrawal', 'ブランド退会時'), ('on_contract_end', '契約終了時'), ('on_withdrawal', '退会時')], default='once', help_text='割引が終了する条件', max_length=30, verbose_name='終了条件'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_employee_discount',
            field=models.BooleanField(default=False, help_text='社員の場合、自動的に適用される割引', verbose_name='社割（社員自動適用）'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='毎月繰り返し適用するか', verbose_name='毎月適用'),
        ),
        migrations.AddField(
            model_name='discount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', '割合'), ('fixed', '固定金額')], default='fixed', max_length=20, verbose_name='計算種別'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('employee', '社割'), ('sibling', '兄弟割引'), ('multi_subject', '複数科目割引'), ('campaign', 'キャンペーン'), ('early_enrollment', '早期入会割引'), ('referral', '紹介割引'), ('other', 'その他')], default='other', max_length=20, verbose_name='割引種別'),
        ),
    ]
