# Generated by Django 4.2.26 on 2025-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0031_add_discount_master_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationenrollment",
            name="billing_month",
            field=models.CharField(
                blank=True,
                help_text="請求対象月（YYYY-MM形式）",
                max_length=7,
                null=True,
                verbose_name="請求月",
            ),
        ),
        migrations.AddField(
            model_name="seminarenrollment",
            name="billing_month",
            field=models.CharField(
                blank=True,
                help_text="請求対象月（YYYY-MM形式）",
                max_length=7,
                null=True,
                verbose_name="請求月",
            ),
        ),
    ]
