# Generated by Django 4.2.27 on 2025-12-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_add_billing_month_to_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mile',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='マイル'),
        ),
    ]
