# Generated by Django 4.2.27 on 2025-12-25 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_permission_models'),
        ('contracts', '0033_course_mile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='billing_price_apr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='4月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_aug',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='8月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_dec',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='12月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_feb',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='2月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_jan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='1月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_jul',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='7月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_jun',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='6月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_mar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='3月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_may',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='5月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_nov',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='11月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_oct',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='10月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='billing_price_sep',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='9月請求価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='discount_max',
            field=models.IntegerField(default=0, verbose_name='割引MAX(%)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_apr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='4月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_aug',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='8月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_dec',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='12月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_feb',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='2月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_jan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='1月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_jul',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='7月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_jun',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='6月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_mar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='3月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_may',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='5月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_nov',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='11月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_oct',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='10月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='enrollment_price_sep',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='9月入会者価格'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='is_required',
            field=models.BooleanField(default=False, help_text='コースに紐づく必須講習の場合はTrue', verbose_name='必須講習'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='mile',
            field=models.IntegerField(default=0, verbose_name='マイル'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='old_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='旧システムID'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='per_ticket_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='チケット単価'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_name_short',
            field=models.CharField(blank=True, max_length=50, verbose_name='講習名（短縮）'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='tax_type',
            field=models.CharField(choices=[('1', '課税'), ('2', '非課税'), ('3', '不課税')], default='1', max_length=1, verbose_name='税区分'),
        ),
        migrations.CreateModel(
            name='CourseSeminar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='会社ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False, help_text='このコースで必須の講習会かどうか', verbose_name='必須')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_seminars', to='contracts.course', verbose_name='コース')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_seminars', to='contracts.seminar', verbose_name='講習')),
                ('tenant_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'T11b_コース講習紐づけ',
                'verbose_name_plural': 'T11b_コース講習紐づけ',
                'db_table': 't11b_course_seminars',
                'unique_together': {('tenant_id', 'course', 'seminar')},
            },
        ),
    ]
