# Generated by Django 4.2.27 on 2025-12-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_add_payment_provider_to_guardian'),
        ('contracts', '0034_extend_seminar_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant_id', 'contract_no', 'student')},
        ),
    ]
