# Generated by Django 4.2.27 on 2026-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_alter_contract_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_type',
            field=models.CharField(choices=[('eiken', '英検'), ('kanken', '漢検'), ('suken', '数検'), ('soroban', '珠算検定'), ('anzan', '暗算検定'), ('other', 'その他')], default='other', max_length=20, verbose_name='検定種別'),
        ),
    ]
