# Generated by Django 4.2.27 on 2026-01-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_add_soroban_certification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='calendar_code',
            field=models.CharField(blank=True, help_text='検定期間をカレンダーから取得する場合に指定（例: 1021_SOR）', max_length=50, verbose_name='カレンダーコード'),
        ),
        migrations.AddField(
            model_name='certification',
            name='purchase_deadline_days',
            field=models.IntegerField(default=7, help_text='検定開始日の何日前まで購入可能か（デフォルト: 7日前）', verbose_name='購入締切日数'),
        ),
    ]
