# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "出席"),
                            ("absent", "欠席"),
                            ("late", "遅刻"),
                            ("early_leave", "早退"),
                            ("absent_notice", "欠席（連絡あり）"),
                            ("makeup", "振替"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="出席状況",
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="入室時刻"),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="退室時刻"),
                ),
                (
                    "absence_reason",
                    models.TextField(blank=True, verbose_name="欠席理由"),
                ),
                (
                    "absence_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="欠席連絡日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "出席記録",
                "verbose_name_plural": "出席記録",
                "db_table": "t19_attendances",
            },
        ),
        migrations.CreateModel(
            name="GroupLessonEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "集団授業受講者",
                "verbose_name_plural": "集団授業受講者",
                "db_table": "t13_group_enrollments",
            },
        ),
        migrations.CreateModel(
            name="LessonRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(blank=True, null=True, verbose_name="実開始時刻"),
                ),
                (
                    "actual_end_time",
                    models.TimeField(blank=True, null=True, verbose_name="実終了時刻"),
                ),
                (
                    "actual_duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="実時間（分）"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="授業内容")),
                ("homework", models.TextField(blank=True, verbose_name="宿題")),
                (
                    "next_lesson_plan",
                    models.TextField(blank=True, verbose_name="次回予定"),
                ),
                (
                    "understanding_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "優秀"),
                            ("good", "良好"),
                            ("average", "普通"),
                            ("below_average", "やや不足"),
                            ("poor", "要改善"),
                        ],
                        max_length=20,
                        verbose_name="理解度",
                    ),
                ),
                (
                    "attitude_evaluation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "優秀"),
                            ("good", "良好"),
                            ("average", "普通"),
                            ("below_average", "やや不足"),
                            ("poor", "要改善"),
                        ],
                        max_length=20,
                        verbose_name="態度評価",
                    ),
                ),
                (
                    "homework_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "優秀"),
                            ("good", "良好"),
                            ("average", "普通"),
                            ("below_average", "やや不足"),
                            ("poor", "要改善"),
                        ],
                        max_length=20,
                        verbose_name="宿題状況",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="講師コメント"),
                ),
                (
                    "internal_memo",
                    models.TextField(blank=True, verbose_name="内部メモ"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記録日時"),
                ),
            ],
            options={
                "verbose_name": "授業実績",
                "verbose_name_plural": "授業実績",
                "db_table": "t14_lesson_records",
            },
        ),
        migrations.CreateModel(
            name="LessonSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("individual", "個別指導"),
                            ("group", "集団授業"),
                            ("online", "オンライン"),
                            ("self_study", "自習"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="授業種別",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "class_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="クラス名"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="定員"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("confirmed", "確定"),
                            ("in_progress", "実施中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "授業スケジュール",
                "verbose_name_plural": "授業スケジュール",
                "db_table": "t13_lesson_schedules",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_code",
                    models.CharField(max_length=10, verbose_name="時限コード"),
                ),
                ("slot_name", models.CharField(max_length=50, verbose_name="時限名")),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="時間（分）"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(blank=True, null=True, verbose_name="曜日"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="schools.school",
                        verbose_name="校舎",
                    ),
                ),
            ],
            options={
                "verbose_name": "時間割",
                "verbose_name_plural": "時間割",
                "db_table": "t15_time_slots",
                "ordering": ["sort_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="MakeupLesson",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(blank=True, null=True, verbose_name="希望日"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "申請中"),
                            ("approved", "承認"),
                            ("scheduled", "予定確定"),
                            ("completed", "完了"),
                            ("rejected", "却下"),
                            ("cancelled", "キャンセル"),
                            ("expired", "期限切れ"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="有効期限"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="処理日時"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="振替理由")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "makeup_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_to",
                        to="lessons.lessonschedule",
                        verbose_name="振替先スケジュール",
                    ),
                ),
                (
                    "original_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeup_from",
                        to="lessons.lessonschedule",
                        verbose_name="元スケジュール",
                    ),
                ),
                (
                    "preferred_time_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_requests",
                        to="lessons.timeslot",
                        verbose_name="希望時間割",
                    ),
                ),
            ],
            options={
                "verbose_name": "振替",
                "verbose_name_plural": "振替",
                "db_table": "t20_makeup_lessons",
                "ordering": ["-requested_at"],
            },
        ),
    ]
