# Generated by Django 4.2.26 on 2025-12-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("hr", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
        ("schools", "0001_initial"),
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="makeuplesson",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_makeups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="処理者",
            ),
        ),
        migrations.AddField(
            model_name="makeuplesson",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makeup_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申請者",
            ),
        ),
        migrations.AddField(
            model_name="makeuplesson",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makeup_lessons",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="schools.classroom",
                verbose_name="教室",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="contracts.contract",
                verbose_name="契約",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_schedules",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="student_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="contracts.studentitem",
                verbose_name="生徒商品",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_schedules",
                to="schools.subject",
                verbose_name="教科",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="hr.staff",
                verbose_name="担当講師",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="lessons.timeslot",
                verbose_name="時間割",
            ),
        ),
        migrations.AddField(
            model_name="lessonrecord",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="記録者",
            ),
        ),
        migrations.AddField(
            model_name="lessonrecord",
            name="schedule",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record",
                to="lessons.lessonschedule",
                verbose_name="スケジュール",
            ),
        ),
        migrations.AddField(
            model_name="grouplessonenrollment",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="lessons.lessonschedule",
                verbose_name="スケジュール",
            ),
        ),
        migrations.AddField(
            model_name="grouplessonenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_enrollments",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="lessons.lessonschedule",
                verbose_name="スケジュール",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonschedule",
            index=models.Index(
                fields=["date", "school"], name="t13_lesson__date_71518d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonschedule",
            index=models.Index(
                fields=["teacher", "date"], name="t13_lesson__teacher_9d02b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonschedule",
            index=models.Index(
                fields=["student", "date"], name="t13_lesson__student_d46a81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouplessonenrollment",
            unique_together={("schedule", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("schedule", "student")},
        ),
    ]
