# Generated by Django 4.2.26 on 2025-12-04 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_classroom_capacity"),
        ("lessons", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCalendar",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calendar_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="カレンダーコード"
                    ),
                ),
                (
                    "calendar_name",
                    models.CharField(max_length=100, verbose_name="カレンダー名"),
                ),
                (
                    "pattern_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="パターンコード"
                    ),
                ),
                ("year", models.IntegerField(default=2024, verbose_name="年度")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_calendars",
                        to="schools.brand",
                        verbose_name="ブランド",
                    ),
                ),
            ],
            options={
                "verbose_name": "開講カレンダー",
                "verbose_name_plural": "開講カレンダー",
                "db_table": "t13a_lesson_calendars",
                "ordering": ["sort_order", "calendar_code"],
            },
        ),
        migrations.CreateModel(
            name="LessonCalendarDay",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, verbose_name="テナントID"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("day_of_week", models.CharField(max_length=3, verbose_name="曜日")),
                (
                    "display_label",
                    models.CharField(
                        blank=True,
                        help_text="例: 水A1, 月1, 休",
                        max_length=50,
                        verbose_name="保護者カレンダー表示",
                    ),
                ),
                ("is_open", models.BooleanField(default=False, verbose_name="開講日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "開講"),
                            ("closed", "休講"),
                            ("holiday", "祝日休"),
                            ("special", "特別日程"),
                        ],
                        default="closed",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "transfer_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allowed", "振替可"),
                            ("not_allowed", "振替不可"),
                            ("conditional", "条件付き可"),
                        ],
                        default="allowed",
                        max_length=20,
                        verbose_name="振替ステータス",
                    ),
                ),
                (
                    "transfer_reject_reason",
                    models.CharField(
                        blank=True,
                        help_text="例: 初回授業につき",
                        max_length=100,
                        verbose_name="振替拒否理由",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True,
                        help_text="例: A, B（週パターン）",
                        max_length=10,
                        verbose_name="チケット券種",
                    ),
                ),
                (
                    "ticket_issue_count",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="権利発券数"
                    ),
                ),
                (
                    "ticket_type_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="チケット券種No"
                    ),
                ),
                (
                    "ticket_valid_days",
                    models.IntegerField(
                        blank=True, default=90, null=True, verbose_name="有効期限（日）"
                    ),
                ),
                ("notice", models.TextField(blank=True, verbose_name="お知らせ")),
                (
                    "auto_send_notice",
                    models.BooleanField(default=False, verbose_name="自動お知らせ送信"),
                ),
                (
                    "holiday_name",
                    models.CharField(blank=True, max_length=50, verbose_name="祝日名"),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="lessons.lessoncalendar",
                        verbose_name="カレンダー",
                    ),
                ),
            ],
            options={
                "verbose_name": "開講カレンダー日",
                "verbose_name_plural": "開講カレンダー日",
                "db_table": "t13b_lesson_calendar_days",
                "ordering": ["calendar", "date"],
                "indexes": [
                    models.Index(fields=["date"], name="t13b_lesson_date_59f546_idx"),
                    models.Index(
                        fields=["calendar", "is_open"],
                        name="t13b_lesson_calenda_695a90_idx",
                    ),
                ],
                "unique_together": {("calendar", "date")},
            },
        ),
    ]
