# Generated by Django 4.2.26 on 2025-12-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("lessons", "0003_add_lesson_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="grouplessonenrollment",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="lessoncalendar",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="lessoncalendarday",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="lessonrecord",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="makeuplesson",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
    ]
