# Generated by Django 4.2.26 on 2025-12-12 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0013_add_grade_to_class_schedule"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0004_add_task_id_ref"),
        ("lessons", "0005_add_absence_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessoncalendar",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="lessoncalendar",
            name="tenant_ref",
        ),
        migrations.AlterUniqueTogether(
            name="lessoncalendarday",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessoncalendarday",
            name="calendar",
        ),
        migrations.RemoveField(
            model_name="lessoncalendarday",
            name="tenant_ref",
        ),
        migrations.RemoveIndex(
            model_name="lessonschedule",
            name="t13_lesson__date_71518d_idx",
        ),
        migrations.RemoveIndex(
            model_name="lessonschedule",
            name="t13_lesson__teacher_9d02b0_idx",
        ),
        migrations.RemoveIndex(
            model_name="lessonschedule",
            name="t13_lesson__student_d46a81_idx",
        ),
        migrations.RemoveField(
            model_name="lessonschedule",
            name="student_item",
        ),
        migrations.AddField(
            model_name="absenceticket",
            name="tenant_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="lessonschedule",
            name="contract_detail_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="契約詳細ID"),
        ),
        # Removed: tenant_id type change (already integer in DB)
        # migrations.AlterField(
        #     model_name="absenceticket",
        #     name="tenant_id",
        #     field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        # ),
        migrations.AlterField(
            model_name="lessonrecord",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="記録者",
            ),
        ),
        migrations.AlterField(
            model_name="lessonschedule",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_schedules",
                to="schools.school",
                verbose_name="校舎",
            ),
        ),
        migrations.AlterField(
            model_name="lessonschedule",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_schedules",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AlterField(
            model_name="lessonschedule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules",
                to="schools.subject",
                verbose_name="教科",
            ),
        ),
        migrations.AlterField(
            model_name="lessonschedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_schedules_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="講師",
            ),
        ),
        migrations.AlterField(
            model_name="makeuplesson",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makeup_processed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="処理者",
            ),
        ),
        migrations.DeleteModel(
            name="LessonCalendar",
        ),
        migrations.DeleteModel(
            name="LessonCalendarDay",
        ),
    ]
