# Generated by Django 4.2.26 on 2025-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_add_student_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absenceticket",
            name="tenant_id",
            field=models.UUIDField(db_index=True, verbose_name="テナントID"),
        ),
    ]
