# Generated by Django 4.2.27 on 2025-12-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_first_fiscal_year_free'),
        ('lessons', '0007_add_additional_ticket_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceticket',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='absenceticket',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='grouplessonenrollment',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='grouplessonenrollment',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='makeuplesson',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='makeuplesson',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tenant_id',
            field=models.UUIDField(db_index=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tenant_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='会社'),
        ),
    ]
